version: 2
updates:
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: quarterly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: quarterly
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: quarterly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: npm
    directories:
      - docs
      - npm/*
      - ui
    schedule:
      interval: monthly
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
