# goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - dir: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - netbsd
      # - windows
    goarch:
      - "amd64"
      - "386"
      - "arm"
      - "arm64"
      - "ppc64le"
      - "s390x"
    goarm:
      - "6"
      - "7"

release:
  mode: keep-existing

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - repository:
      owner: dagu-org
      name: homebrew-brew
    directory: Formula
    homepage: "https://github.com/dagu-org/dagu"
    description: "Dagu is a compact, portable, and language-agnostic workflow engine."
    license: "GNU General Public License v3.0"
    custom_block: |
      service do
        run [opt_bin/"dagu", "start-all"]
        keep_alive true
        error_log_path var/"log/dagu.log"
        log_path var/"log/dagu.log"
        working_dir var
      end

  # Deprecated brew tap:
  - repository:
      owner: yohamta
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/dagu-org/dagu"
    description: "Dagu is a compact, portable, and language-agnostic workflow engine."
    license: "GNU General Public License v3.0"
    custom_block: |
      service do
        run [opt_bin/"dagu", "start-all"]
        keep_alive true
        error_log_path var/"log/dagu.log"
        log_path var/"log/dagu.log"
        working_dir var
      end

snapcrafts:
  - name: dagu
    title: Dagu
    publish: true
    summary: "A compact, portable, and language-agnostic workflow engine."
    description: "Dagu is a compact, portable, and language-agnostic workflow engine."
    confinement: strict
    grade: stable
    base: core22
    license: "GPL-3.0"
    apps:
      dagu:
        command: dagu start-all
        daemon: simple
        restart_condition: "always"
        plugs:
          - network
          - home
          - personal-files
