# goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: dagu
    dir: ./cmd
    binary: dagu
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - windows
    goarch:
      - "amd64"
      - "386"
      - "arm"
      - "arm64"
      - "ppc64le"
      - "s390x"
    goarm:
      - "6"
      - "7"
    ignore:
      # modernc.org/libc does not compile on 32-bit FreeBSD/OpenBSD.
      # FreeBSD 15.0 removed 32-bit platform support.
      - goos: freebsd
        goarch: "386"
      - goos: freebsd
        goarch: arm
        goarm: "6"
      - goos: freebsd
        goarch: arm
        goarm: "7"
      - goos: openbsd
        goarch: "386"
      - goos: openbsd
        goarch: arm
        goarm: "6"
      - goos: openbsd
        goarch: arm
        goarm: "7"
      # Go does not support windows/arm.
      - goos: windows
        goarch: arm
        goarm: "6"
      - goos: windows
        goarch: arm
        goarm: "7"

release:
  mode: keep-existing
  prerelease: auto

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - skip_upload: auto
    repository:
      owner: dagu-org
      name: homebrew-brew
    directory: Formula
    homepage: "https://github.com/dagu-org/dagu"
    description: "A compact, portable, and language-agnostic workflow engine"
    license: "GNU General Public License v3.0"
    custom_block: |
      service do
        run [opt_bin/"dagu", "start-all"]
        keep_alive true
        error_log_path var/"log/dagu.log"
        log_path var/"log/dagu.log"
        working_dir var
      end

  # Deprecated brew tap:
  - skip_upload: auto
    repository:
      owner: yohamta
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/dagu-org/dagu"
    description: "A compact, portable, and language-agnostic workflow engine"
    license: "GNU General Public License v3.0"
    custom_block: |
      service do
        run [opt_bin/"dagu", "start-all"]
        keep_alive true
        error_log_path var/"log/dagu.log"
        log_path var/"log/dagu.log"
        working_dir var
      end

