openapi: "3.0.0"
info:
  version: 1.0.0
  title: Dagu API
  description: API for controlling Dagu server
  contact:
    name: Yota Hamada

servers:
  - url: "{schema}://localhost:8080/api/v0"
    description: Local
    variables:
      schema:
        default: http
        enum: [http, https]

tags:
  - name: "legacy"
    description: "Deprecated: Operations for managing and running DAGs"
  - name: "system"
    description: "System operations"

paths:
  /health:
    get:
      summary: "Health check endpoint"
      description: "Returns the health status of the server"
      operationId: "getHealth"
      tags:
        - system
      responses:
        "200":
          description: "Health check successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        default:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          description: "Error code"
        message:
          type: string
          description: "Error message"
        details:
          type: object
          description: "Additional error details"
      required:
        - code
        - message

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: ["healthy", "unhealthy"]
          description: "Overall health status of the server"
        version:
          type: string
          description: "Current version of the server"
        uptime:
          type: integer
          description: "Server uptime in seconds"
        timestamp:
          type: string
          description: "Current server time"
      required:
        - status
        - version
        - uptime
        - timestamp
