coverage:
  ignore:
    - "internal/admin/handlers"
  status:
    project:
      default:
        if_ci_failed: success
        threshold: 5%
    patch:
      default:
        if_ci_failed: success
        threshold: 20%
github_checks:
    annotations: false
