# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: api
output: api/v1/api.gen.go
generate:
  models: true
  chi-server: true
  embedded-spec: true
  strict-server: true
compatibility:
  apply-chi-middleware-first-to-last: true
  always-prefix-enum-values: true
