// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Dagu",
    "version": "0.0.1"
  },
  "host": "localhost:8080",
  "basePath": "/api/v1",
  "paths": {
    "/dags": {
      "get": {
        "description": "Returns a list of DAGs.",
        "produces": [
          "application/json"
        ],
        "operationId": "listDags",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/listDagsResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      },
      "post": {
        "description": "Creates a new DAG.",
        "produces": [
          "application/json"
        ],
        "operationId": "createDag",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "action",
                "value"
              ],
              "properties": {
                "action": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/createDagResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      }
    },
    "/dags/{dagId}": {
      "get": {
        "description": "Returns details of a DAG.",
        "produces": [
          "application/json"
        ],
        "operationId": "getDagDetails",
        "parameters": [
          {
            "type": "string",
            "name": "dagId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "tab",
            "in": "query"
          },
          {
            "type": "string",
            "name": "file",
            "in": "query"
          },
          {
            "type": "string",
            "name": "step",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/getDagDetailsResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      },
      "post": {
        "description": "Performs an action on a DAG.",
        "produces": [
          "application/json"
        ],
        "operationId": "postDagAction",
        "parameters": [
          {
            "type": "string",
            "name": "dagId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "action"
              ],
              "properties": {
                "action": {
                  "type": "string",
                  "enum": [
                    "start",
                    "suspend",
                    "stop",
                    "retry",
                    "mark-success",
                    "mark-failed",
                    "save",
                    "rename"
                  ]
                },
                "params": {
                  "type": "string"
                },
                "requestId": {
                  "type": "string"
                },
                "step": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/postDagActionResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      },
      "delete": {
        "description": "Deletes a DAG.",
        "produces": [
          "application/json"
        ],
        "operationId": "deleteDag",
        "parameters": [
          {
            "type": "string",
            "name": "dagId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      }
    },
    "/search": {
      "get": {
        "description": "Searches for DAGs.",
        "produces": [
          "application/json"
        ],
        "operationId": "searchDags",
        "parameters": [
          {
            "type": "string",
            "name": "q",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/searchDagsResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiError": {
      "type": "object",
      "required": [
        "message",
        "detailedMessage"
      ],
      "properties": {
        "detailedMessage": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "condition": {
      "type": "object",
      "properties": {
        "Condition": {
          "type": "string"
        },
        "Expected": {
          "type": "string"
        }
      }
    },
    "createDagResponse": {
      "type": "object",
      "required": [
        "DagID"
      ],
      "properties": {
        "DagID": {
          "type": "string"
        }
      }
    },
    "dag": {
      "type": "object",
      "required": [
        "Group",
        "Name",
        "Schedule",
        "Description",
        "Params",
        "DefaultParams",
        "Tags"
      ],
      "properties": {
        "DefaultParams": {
          "type": "string"
        },
        "Description": {
          "type": "string"
        },
        "Group": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "Params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Schedule": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/schedule"
          }
        },
        "Tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "dagDetail": {
      "type": "object",
      "required": [
        "Location",
        "Group",
        "Name",
        "Schedule",
        "Description",
        "Env",
        "LogDir",
        "HandlerOn",
        "Steps",
        "Delay",
        "HistRetentionDays",
        "Preconditions",
        "MaxActiveRuns",
        "Params",
        "DefaultParams",
        "Tags"
      ],
      "properties": {
        "DefaultParams": {
          "type": "string"
        },
        "Delay": {
          "type": "integer"
        },
        "Description": {
          "type": "string"
        },
        "Env": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Group": {
          "type": "string"
        },
        "HandlerOn": {
          "$ref": "#/definitions/handlerOn"
        },
        "HistRetentionDays": {
          "type": "integer"
        },
        "Location": {
          "type": "string"
        },
        "LogDir": {
          "type": "string"
        },
        "MaxActiveRuns": {
          "type": "integer"
        },
        "Name": {
          "type": "string"
        },
        "Params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Preconditions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/condition"
          }
        },
        "Schedule": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/schedule"
          }
        },
        "Steps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/stepObject"
          }
        },
        "Tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "dagListItem": {
      "type": "object",
      "required": [
        "File",
        "Dir",
        "DAG",
        "Status",
        "Suspended",
        "Error",
        "ErrorT"
      ],
      "properties": {
        "DAG": {
          "$ref": "#/definitions/dag"
        },
        "Dir": {
          "type": "string"
        },
        "Error": {
          "type": "string"
        },
        "ErrorT": {
          "type": "string"
        },
        "File": {
          "type": "string"
        },
        "Status": {
          "$ref": "#/definitions/dagStatus"
        },
        "Suspended": {
          "type": "boolean"
        }
      }
    },
    "dagLogGridItem": {
      "type": "object",
      "required": [
        "Name",
        "Vals"
      ],
      "properties": {
        "Name": {
          "type": "string"
        },
        "Vals": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      }
    },
    "dagLogResponse": {
      "type": "object",
      "required": [
        "GridData",
        "Logs"
      ],
      "properties": {
        "GridData": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/dagLogGridItem"
          }
        },
        "Logs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/dagStatusFile"
          }
        }
      }
    },
    "dagSchedulerLogResponse": {
      "type": "object",
      "required": [
        "LogFile",
        "Content"
      ],
      "properties": {
        "Content": {
          "type": "string"
        },
        "LogFile": {
          "type": "string"
        }
      }
    },
    "dagStatus": {
      "type": "object",
      "required": [
        "RequestId",
        "Name",
        "Status",
        "StatusText",
        "Pid",
        "StartedAt",
        "FinishedAt",
        "Log",
        "Params"
      ],
      "properties": {
        "FinishedAt": {
          "type": "string"
        },
        "Log": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "Params": {
          "type": "string"
        },
        "Pid": {
          "type": "integer"
        },
        "RequestId": {
          "type": "string"
        },
        "StartedAt": {
          "type": "string"
        },
        "Status": {
          "type": "integer"
        },
        "StatusText": {
          "type": "string"
        }
      }
    },
    "dagStatusDetail": {
      "type": "object",
      "required": [
        "RequestId",
        "Name",
        "Status",
        "StatusText",
        "Pid",
        "Nodes",
        "OnExit",
        "OnSuccess",
        "OnFailure",
        "OnCancel",
        "StartedAt",
        "FinishedAt",
        "Log",
        "Params"
      ],
      "properties": {
        "FinishedAt": {
          "type": "string"
        },
        "Log": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "Nodes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/statusNode"
          }
        },
        "OnCancel": {
          "$ref": "#/definitions/statusNode"
        },
        "OnExit": {
          "$ref": "#/definitions/statusNode"
        },
        "OnFailure": {
          "$ref": "#/definitions/statusNode"
        },
        "OnSuccess": {
          "$ref": "#/definitions/statusNode"
        },
        "Params": {
          "type": "string"
        },
        "Pid": {
          "type": "integer"
        },
        "RequestId": {
          "type": "string"
        },
        "StartedAt": {
          "type": "string"
        },
        "Status": {
          "type": "integer"
        },
        "StatusText": {
          "type": "string"
        }
      }
    },
    "dagStatusFile": {
      "type": "object",
      "required": [
        "File"
      ],
      "properties": {
        "File": {
          "type": "string"
        },
        "Status": {
          "$ref": "#/definitions/dagStatusDetail"
        }
      }
    },
    "dagStatusWithDetails": {
      "type": "object",
      "required": [
        "File",
        "Dir",
        "DAG",
        "Status",
        "Suspended",
        "Error",
        "ErrorT"
      ],
      "properties": {
        "DAG": {
          "$ref": "#/definitions/dagDetail"
        },
        "Dir": {
          "type": "string"
        },
        "Error": {
          "type": "string"
        },
        "ErrorT": {
          "type": "string"
        },
        "File": {
          "type": "string"
        },
        "Status": {
          "$ref": "#/definitions/dagStatusDetail"
        },
        "Suspended": {
          "type": "boolean"
        }
      }
    },
    "dagStepLogResponse": {
      "type": "object",
      "required": [
        "Step",
        "LogFile",
        "Content"
      ],
      "properties": {
        "Content": {
          "type": "string"
        },
        "LogFile": {
          "type": "string"
        },
        "Step": {
          "$ref": "#/definitions/statusNode"
        }
      }
    },
    "getDagDetailsResponse": {
      "type": "object",
      "required": [
        "Title",
        "DAG",
        "Tab",
        "Graph",
        "Definition",
        "LogData",
        "LogUrl",
        "StepLog",
        "ScLog",
        "Errors"
      ],
      "properties": {
        "DAG": {
          "$ref": "#/definitions/dagStatusWithDetails"
        },
        "Definition": {
          "type": "string"
        },
        "Errors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Graph": {
          "type": "string"
        },
        "LogData": {
          "$ref": "#/definitions/dagLogResponse"
        },
        "LogUrl": {
          "type": "string"
        },
        "ScLog": {
          "$ref": "#/definitions/dagSchedulerLogResponse"
        },
        "StepLog": {
          "$ref": "#/definitions/dagStepLogResponse"
        },
        "Tab": {
          "type": "string"
        },
        "Title": {
          "type": "string"
        }
      }
    },
    "handlerOn": {
      "type": "object",
      "properties": {
        "Cancel": {
          "$ref": "#/definitions/stepObject"
        },
        "Exit": {
          "$ref": "#/definitions/stepObject"
        },
        "Failure": {
          "$ref": "#/definitions/stepObject"
        },
        "Success": {
          "$ref": "#/definitions/stepObject"
        }
      }
    },
    "listDagsResponse": {
      "type": "object",
      "required": [
        "DAGs",
        "Errors",
        "HasError"
      ],
      "properties": {
        "DAGs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/dagListItem"
          }
        },
        "Errors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "HasError": {
          "type": "boolean"
        }
      }
    },
    "postDagActionResponse": {
      "type": "object",
      "properties": {
        "NewDagID": {
          "type": "string"
        }
      }
    },
    "repeatPolicy": {
      "type": "object",
      "properties": {
        "Interval": {
          "type": "integer"
        },
        "Repeat": {
          "type": "boolean"
        }
      }
    },
    "schedule": {
      "type": "object",
      "required": [
        "Expression"
      ],
      "properties": {
        "Expression": {
          "type": "string"
        }
      }
    },
    "searchDagsMatchItem": {
      "type": "object",
      "properties": {
        "Line": {
          "type": "string"
        },
        "LineNumber": {
          "type": "integer"
        },
        "StartLine": {
          "type": "integer"
        }
      }
    },
    "searchDagsResponse": {
      "type": "object",
      "required": [
        "Results",
        "Errors"
      ],
      "properties": {
        "Errors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/searchDagsResultItem"
          }
        }
      }
    },
    "searchDagsResultItem": {
      "type": "object",
      "properties": {
        "DAG": {
          "$ref": "#/definitions/dag"
        },
        "Matches": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/searchDagsMatchItem"
          }
        },
        "Name": {
          "type": "string"
        }
      }
    },
    "statusNode": {
      "type": "object",
      "required": [
        "Step",
        "Log",
        "StartedAt",
        "FinishedAt",
        "Status",
        "RetryCount",
        "DoneCount",
        "Error",
        "StatusText"
      ],
      "properties": {
        "DoneCount": {
          "type": "integer"
        },
        "Error": {
          "type": "string"
        },
        "FinishedAt": {
          "type": "string"
        },
        "Log": {
          "type": "string"
        },
        "RetryCount": {
          "type": "integer"
        },
        "StartedAt": {
          "type": "string"
        },
        "Status": {
          "type": "integer"
        },
        "StatusText": {
          "type": "string"
        },
        "Step": {
          "$ref": "#/definitions/stepObject"
        }
      }
    },
    "stepObject": {
      "type": "object",
      "required": [
        "Name",
        "Description",
        "Variables",
        "Dir",
        "CmdWithArgs",
        "Command",
        "Script",
        "Stdout",
        "Stderr",
        "Output",
        "Args",
        "Depends",
        "RepeatPolicy",
        "MailOnError",
        "Preconditions"
      ],
      "properties": {
        "Args": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "CmdWithArgs": {
          "type": "string"
        },
        "Command": {
          "type": "string"
        },
        "Depends": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Description": {
          "type": "string"
        },
        "Dir": {
          "type": "string"
        },
        "MailOnError": {
          "type": "boolean"
        },
        "Name": {
          "type": "string"
        },
        "Output": {
          "type": "string"
        },
        "Preconditions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/condition"
          }
        },
        "RepeatPolicy": {
          "$ref": "#/definitions/repeatPolicy"
        },
        "Script": {
          "type": "string"
        },
        "Stderr": {
          "type": "string"
        },
        "Stdout": {
          "type": "string"
        },
        "Variables": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Dagu",
    "version": "0.0.1"
  },
  "host": "localhost:8080",
  "basePath": "/api/v1",
  "paths": {
    "/dags": {
      "get": {
        "description": "Returns a list of DAGs.",
        "produces": [
          "application/json"
        ],
        "operationId": "listDags",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/listDagsResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      },
      "post": {
        "description": "Creates a new DAG.",
        "produces": [
          "application/json"
        ],
        "operationId": "createDag",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "action",
                "value"
              ],
              "properties": {
                "action": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/createDagResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      }
    },
    "/dags/{dagId}": {
      "get": {
        "description": "Returns details of a DAG.",
        "produces": [
          "application/json"
        ],
        "operationId": "getDagDetails",
        "parameters": [
          {
            "type": "string",
            "name": "dagId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "tab",
            "in": "query"
          },
          {
            "type": "string",
            "name": "file",
            "in": "query"
          },
          {
            "type": "string",
            "name": "step",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/getDagDetailsResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      },
      "post": {
        "description": "Performs an action on a DAG.",
        "produces": [
          "application/json"
        ],
        "operationId": "postDagAction",
        "parameters": [
          {
            "type": "string",
            "name": "dagId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "action"
              ],
              "properties": {
                "action": {
                  "type": "string",
                  "enum": [
                    "start",
                    "suspend",
                    "stop",
                    "retry",
                    "mark-success",
                    "mark-failed",
                    "save",
                    "rename"
                  ]
                },
                "params": {
                  "type": "string"
                },
                "requestId": {
                  "type": "string"
                },
                "step": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/postDagActionResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      },
      "delete": {
        "description": "Deletes a DAG.",
        "produces": [
          "application/json"
        ],
        "operationId": "deleteDag",
        "parameters": [
          {
            "type": "string",
            "name": "dagId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      }
    },
    "/search": {
      "get": {
        "description": "Searches for DAGs.",
        "produces": [
          "application/json"
        ],
        "operationId": "searchDags",
        "parameters": [
          {
            "type": "string",
            "name": "q",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/searchDagsResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/ApiError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiError": {
      "type": "object",
      "required": [
        "message",
        "detailedMessage"
      ],
      "properties": {
        "detailedMessage": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "condition": {
      "type": "object",
      "properties": {
        "Condition": {
          "type": "string"
        },
        "Expected": {
          "type": "string"
        }
      }
    },
    "createDagResponse": {
      "type": "object",
      "required": [
        "DagID"
      ],
      "properties": {
        "DagID": {
          "type": "string"
        }
      }
    },
    "dag": {
      "type": "object",
      "required": [
        "Group",
        "Name",
        "Schedule",
        "Description",
        "Params",
        "DefaultParams",
        "Tags"
      ],
      "properties": {
        "DefaultParams": {
          "type": "string"
        },
        "Description": {
          "type": "string"
        },
        "Group": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "Params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Schedule": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/schedule"
          }
        },
        "Tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "dagDetail": {
      "type": "object",
      "required": [
        "Location",
        "Group",
        "Name",
        "Schedule",
        "Description",
        "Env",
        "LogDir",
        "HandlerOn",
        "Steps",
        "Delay",
        "HistRetentionDays",
        "Preconditions",
        "MaxActiveRuns",
        "Params",
        "DefaultParams",
        "Tags"
      ],
      "properties": {
        "DefaultParams": {
          "type": "string"
        },
        "Delay": {
          "type": "integer"
        },
        "Description": {
          "type": "string"
        },
        "Env": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Group": {
          "type": "string"
        },
        "HandlerOn": {
          "$ref": "#/definitions/handlerOn"
        },
        "HistRetentionDays": {
          "type": "integer"
        },
        "Location": {
          "type": "string"
        },
        "LogDir": {
          "type": "string"
        },
        "MaxActiveRuns": {
          "type": "integer"
        },
        "Name": {
          "type": "string"
        },
        "Params": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Preconditions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/condition"
          }
        },
        "Schedule": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/schedule"
          }
        },
        "Steps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/stepObject"
          }
        },
        "Tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "dagListItem": {
      "type": "object",
      "required": [
        "File",
        "Dir",
        "DAG",
        "Status",
        "Suspended",
        "Error",
        "ErrorT"
      ],
      "properties": {
        "DAG": {
          "$ref": "#/definitions/dag"
        },
        "Dir": {
          "type": "string"
        },
        "Error": {
          "type": "string"
        },
        "ErrorT": {
          "type": "string"
        },
        "File": {
          "type": "string"
        },
        "Status": {
          "$ref": "#/definitions/dagStatus"
        },
        "Suspended": {
          "type": "boolean"
        }
      }
    },
    "dagLogGridItem": {
      "type": "object",
      "required": [
        "Name",
        "Vals"
      ],
      "properties": {
        "Name": {
          "type": "string"
        },
        "Vals": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      }
    },
    "dagLogResponse": {
      "type": "object",
      "required": [
        "GridData",
        "Logs"
      ],
      "properties": {
        "GridData": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/dagLogGridItem"
          }
        },
        "Logs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/dagStatusFile"
          }
        }
      }
    },
    "dagSchedulerLogResponse": {
      "type": "object",
      "required": [
        "LogFile",
        "Content"
      ],
      "properties": {
        "Content": {
          "type": "string"
        },
        "LogFile": {
          "type": "string"
        }
      }
    },
    "dagStatus": {
      "type": "object",
      "required": [
        "RequestId",
        "Name",
        "Status",
        "StatusText",
        "Pid",
        "StartedAt",
        "FinishedAt",
        "Log",
        "Params"
      ],
      "properties": {
        "FinishedAt": {
          "type": "string"
        },
        "Log": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "Params": {
          "type": "string"
        },
        "Pid": {
          "type": "integer"
        },
        "RequestId": {
          "type": "string"
        },
        "StartedAt": {
          "type": "string"
        },
        "Status": {
          "type": "integer"
        },
        "StatusText": {
          "type": "string"
        }
      }
    },
    "dagStatusDetail": {
      "type": "object",
      "required": [
        "RequestId",
        "Name",
        "Status",
        "StatusText",
        "Pid",
        "Nodes",
        "OnExit",
        "OnSuccess",
        "OnFailure",
        "OnCancel",
        "StartedAt",
        "FinishedAt",
        "Log",
        "Params"
      ],
      "properties": {
        "FinishedAt": {
          "type": "string"
        },
        "Log": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "Nodes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/statusNode"
          }
        },
        "OnCancel": {
          "$ref": "#/definitions/statusNode"
        },
        "OnExit": {
          "$ref": "#/definitions/statusNode"
        },
        "OnFailure": {
          "$ref": "#/definitions/statusNode"
        },
        "OnSuccess": {
          "$ref": "#/definitions/statusNode"
        },
        "Params": {
          "type": "string"
        },
        "Pid": {
          "type": "integer"
        },
        "RequestId": {
          "type": "string"
        },
        "StartedAt": {
          "type": "string"
        },
        "Status": {
          "type": "integer"
        },
        "StatusText": {
          "type": "string"
        }
      }
    },
    "dagStatusFile": {
      "type": "object",
      "required": [
        "File"
      ],
      "properties": {
        "File": {
          "type": "string"
        },
        "Status": {
          "$ref": "#/definitions/dagStatusDetail"
        }
      }
    },
    "dagStatusWithDetails": {
      "type": "object",
      "required": [
        "File",
        "Dir",
        "DAG",
        "Status",
        "Suspended",
        "Error",
        "ErrorT"
      ],
      "properties": {
        "DAG": {
          "$ref": "#/definitions/dagDetail"
        },
        "Dir": {
          "type": "string"
        },
        "Error": {
          "type": "string"
        },
        "ErrorT": {
          "type": "string"
        },
        "File": {
          "type": "string"
        },
        "Status": {
          "$ref": "#/definitions/dagStatusDetail"
        },
        "Suspended": {
          "type": "boolean"
        }
      }
    },
    "dagStepLogResponse": {
      "type": "object",
      "required": [
        "Step",
        "LogFile",
        "Content"
      ],
      "properties": {
        "Content": {
          "type": "string"
        },
        "LogFile": {
          "type": "string"
        },
        "Step": {
          "$ref": "#/definitions/statusNode"
        }
      }
    },
    "getDagDetailsResponse": {
      "type": "object",
      "required": [
        "Title",
        "DAG",
        "Tab",
        "Graph",
        "Definition",
        "LogData",
        "LogUrl",
        "StepLog",
        "ScLog",
        "Errors"
      ],
      "properties": {
        "DAG": {
          "$ref": "#/definitions/dagStatusWithDetails"
        },
        "Definition": {
          "type": "string"
        },
        "Errors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Graph": {
          "type": "string"
        },
        "LogData": {
          "$ref": "#/definitions/dagLogResponse"
        },
        "LogUrl": {
          "type": "string"
        },
        "ScLog": {
          "$ref": "#/definitions/dagSchedulerLogResponse"
        },
        "StepLog": {
          "$ref": "#/definitions/dagStepLogResponse"
        },
        "Tab": {
          "type": "string"
        },
        "Title": {
          "type": "string"
        }
      }
    },
    "handlerOn": {
      "type": "object",
      "properties": {
        "Cancel": {
          "$ref": "#/definitions/stepObject"
        },
        "Exit": {
          "$ref": "#/definitions/stepObject"
        },
        "Failure": {
          "$ref": "#/definitions/stepObject"
        },
        "Success": {
          "$ref": "#/definitions/stepObject"
        }
      }
    },
    "listDagsResponse": {
      "type": "object",
      "required": [
        "DAGs",
        "Errors",
        "HasError"
      ],
      "properties": {
        "DAGs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/dagListItem"
          }
        },
        "Errors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "HasError": {
          "type": "boolean"
        }
      }
    },
    "postDagActionResponse": {
      "type": "object",
      "properties": {
        "NewDagID": {
          "type": "string"
        }
      }
    },
    "repeatPolicy": {
      "type": "object",
      "properties": {
        "Interval": {
          "type": "integer"
        },
        "Repeat": {
          "type": "boolean"
        }
      }
    },
    "schedule": {
      "type": "object",
      "required": [
        "Expression"
      ],
      "properties": {
        "Expression": {
          "type": "string"
        }
      }
    },
    "searchDagsMatchItem": {
      "type": "object",
      "properties": {
        "Line": {
          "type": "string"
        },
        "LineNumber": {
          "type": "integer"
        },
        "StartLine": {
          "type": "integer"
        }
      }
    },
    "searchDagsResponse": {
      "type": "object",
      "required": [
        "Results",
        "Errors"
      ],
      "properties": {
        "Errors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/searchDagsResultItem"
          }
        }
      }
    },
    "searchDagsResultItem": {
      "type": "object",
      "properties": {
        "DAG": {
          "$ref": "#/definitions/dag"
        },
        "Matches": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/searchDagsMatchItem"
          }
        },
        "Name": {
          "type": "string"
        }
      }
    },
    "statusNode": {
      "type": "object",
      "required": [
        "Step",
        "Log",
        "StartedAt",
        "FinishedAt",
        "Status",
        "RetryCount",
        "DoneCount",
        "Error",
        "StatusText"
      ],
      "properties": {
        "DoneCount": {
          "type": "integer"
        },
        "Error": {
          "type": "string"
        },
        "FinishedAt": {
          "type": "string"
        },
        "Log": {
          "type": "string"
        },
        "RetryCount": {
          "type": "integer"
        },
        "StartedAt": {
          "type": "string"
        },
        "Status": {
          "type": "integer"
        },
        "StatusText": {
          "type": "string"
        },
        "Step": {
          "$ref": "#/definitions/stepObject"
        }
      }
    },
    "stepObject": {
      "type": "object",
      "required": [
        "Name",
        "Description",
        "Variables",
        "Dir",
        "CmdWithArgs",
        "Command",
        "Script",
        "Stdout",
        "Stderr",
        "Output",
        "Args",
        "Depends",
        "RepeatPolicy",
        "MailOnError",
        "Preconditions"
      ],
      "properties": {
        "Args": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "CmdWithArgs": {
          "type": "string"
        },
        "Command": {
          "type": "string"
        },
        "Depends": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Description": {
          "type": "string"
        },
        "Dir": {
          "type": "string"
        },
        "MailOnError": {
          "type": "boolean"
        },
        "Name": {
          "type": "string"
        },
        "Output": {
          "type": "string"
        },
        "Preconditions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/condition"
          }
        },
        "RepeatPolicy": {
          "$ref": "#/definitions/repeatPolicy"
        },
        "Script": {
          "type": "string"
        },
        "Stderr": {
          "type": "string"
        },
        "Stdout": {
          "type": "string"
        },
        "Variables": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}`))
}
