apiVersion: v2
name: dagu
description: A compact, self-contained workflow engine with a web UI
type: application
version: 2.0.4
appVersion: "2.11.1"
kubeVersion: ">=1.19.0-0"
home: https://dagu.sh
icon: https://raw.githubusercontent.com/dagucloud/dagu/3742177d7210d6a1978bb5aa93f4de203bee2b8f/assets/images/brand-mark.png
sources:
  - https://github.com/dagucloud/dagu
maintainers:
  - name: Dagu
    url: https://github.com/dagucloud
keywords:
  - workflow
  - scheduler
  - dag
  - automation
annotations:
  artifacthub.io/license: GPL-3.0-or-later
