// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WorkflowStepLogResponse workflow step log response
//
// swagger:model workflowStepLogResponse
type WorkflowStepLogResponse struct {

	// content
	// Required: true
	Content *string `json:"Content"`

	// log file
	// Required: true
	LogFile *string `json:"LogFile"`

	// step
	// Required: true
	Step *StatusNode `json:"Step"`
}

// Validate validates this workflow step log response
func (m *WorkflowStepLogResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogFile(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStep(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkflowStepLogResponse) validateContent(formats strfmt.Registry) error {

	if err := validate.Required("Content", "body", m.Content); err != nil {
		return err
	}

	return nil
}

func (m *WorkflowStepLogResponse) validateLogFile(formats strfmt.Registry) error {

	if err := validate.Required("LogFile", "body", m.LogFile); err != nil {
		return err
	}

	return nil
}

func (m *WorkflowStepLogResponse) validateStep(formats strfmt.Registry) error {

	if err := validate.Required("Step", "body", m.Step); err != nil {
		return err
	}

	if m.Step != nil {
		if err := m.Step.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Step")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Step")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this workflow step log response based on the context it is used
func (m *WorkflowStepLogResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStep(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkflowStepLogResponse) contextValidateStep(ctx context.Context, formats strfmt.Registry) error {

	if m.Step != nil {

		if err := m.Step.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Step")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Step")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WorkflowStepLogResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkflowStepLogResponse) UnmarshalBinary(b []byte) error {
	var res WorkflowStepLogResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
