// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WorkflowStatusDetail workflow status detail
//
// swagger:model workflowStatusDetail
type WorkflowStatusDetail struct {

	// finished at
	// Required: true
	FinishedAt *string `json:"FinishedAt"`

	// log
	// Required: true
	Log *string `json:"Log"`

	// name
	// Required: true
	Name *string `json:"Name"`

	// nodes
	// Required: true
	Nodes []*StatusNode `json:"Nodes"`

	// on cancel
	// Required: true
	OnCancel *StatusNode `json:"OnCancel"`

	// on exit
	// Required: true
	OnExit *StatusNode `json:"OnExit"`

	// on failure
	// Required: true
	OnFailure *StatusNode `json:"OnFailure"`

	// on success
	// Required: true
	OnSuccess *StatusNode `json:"OnSuccess"`

	// params
	// Required: true
	Params *string `json:"Params"`

	// pid
	// Required: true
	Pid *int64 `json:"Pid"`

	// request Id
	// Required: true
	RequestID *string `json:"RequestId"`

	// started at
	// Required: true
	StartedAt *string `json:"StartedAt"`

	// status
	// Required: true
	Status *int64 `json:"Status"`

	// status text
	// Required: true
	StatusText *string `json:"StatusText"`
}

// Validate validates this workflow status detail
func (m *WorkflowStatusDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFinishedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLog(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNodes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOnCancel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOnExit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOnFailure(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOnSuccess(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParams(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePid(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatusText(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkflowStatusDetail) validateFinishedAt(formats strfmt.Registry) error {

	if err := validate.Required("FinishedAt", "body", m.FinishedAt); err != nil {
		return err
	}

	return nil
}

func (m *WorkflowStatusDetail) validateLog(formats strfmt.Registry) error {

	if err := validate.Required("Log", "body", m.Log); err != nil {
		return err
	}

	return nil
}

func (m *WorkflowStatusDetail) validateName(formats strfmt.Registry) error {

	if err := validate.Required("Name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *WorkflowStatusDetail) validateNodes(formats strfmt.Registry) error {

	if err := validate.Required("Nodes", "body", m.Nodes); err != nil {
		return err
	}

	for i := 0; i < len(m.Nodes); i++ {
		if swag.IsZero(m.Nodes[i]) { // not required
			continue
		}

		if m.Nodes[i] != nil {
			if err := m.Nodes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Nodes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Nodes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *WorkflowStatusDetail) validateOnCancel(formats strfmt.Registry) error {

	if err := validate.Required("OnCancel", "body", m.OnCancel); err != nil {
		return err
	}

	if m.OnCancel != nil {
		if err := m.OnCancel.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("OnCancel")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("OnCancel")
			}
			return err
		}
	}

	return nil
}

func (m *WorkflowStatusDetail) validateOnExit(formats strfmt.Registry) error {

	if err := validate.Required("OnExit", "body", m.OnExit); err != nil {
		return err
	}

	if m.OnExit != nil {
		if err := m.OnExit.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("OnExit")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("OnExit")
			}
			return err
		}
	}

	return nil
}

func (m *WorkflowStatusDetail) validateOnFailure(formats strfmt.Registry) error {

	if err := validate.Required("OnFailure", "body", m.OnFailure); err != nil {
		return err
	}

	if m.OnFailure != nil {
		if err := m.OnFailure.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("OnFailure")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("OnFailure")
			}
			return err
		}
	}

	return nil
}

func (m *WorkflowStatusDetail) validateOnSuccess(formats strfmt.Registry) error {

	if err := validate.Required("OnSuccess", "body", m.OnSuccess); err != nil {
		return err
	}

	if m.OnSuccess != nil {
		if err := m.OnSuccess.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("OnSuccess")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("OnSuccess")
			}
			return err
		}
	}

	return nil
}

func (m *WorkflowStatusDetail) validateParams(formats strfmt.Registry) error {

	if err := validate.Required("Params", "body", m.Params); err != nil {
		return err
	}

	return nil
}

func (m *WorkflowStatusDetail) validatePid(formats strfmt.Registry) error {

	if err := validate.Required("Pid", "body", m.Pid); err != nil {
		return err
	}

	return nil
}

func (m *WorkflowStatusDetail) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("RequestId", "body", m.RequestID); err != nil {
		return err
	}

	return nil
}

func (m *WorkflowStatusDetail) validateStartedAt(formats strfmt.Registry) error {

	if err := validate.Required("StartedAt", "body", m.StartedAt); err != nil {
		return err
	}

	return nil
}

func (m *WorkflowStatusDetail) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("Status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

func (m *WorkflowStatusDetail) validateStatusText(formats strfmt.Registry) error {

	if err := validate.Required("StatusText", "body", m.StatusText); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this workflow status detail based on the context it is used
func (m *WorkflowStatusDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateNodes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOnCancel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOnExit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOnFailure(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOnSuccess(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkflowStatusDetail) contextValidateNodes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Nodes); i++ {

		if m.Nodes[i] != nil {

			if swag.IsZero(m.Nodes[i]) { // not required
				return nil
			}

			if err := m.Nodes[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Nodes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Nodes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *WorkflowStatusDetail) contextValidateOnCancel(ctx context.Context, formats strfmt.Registry) error {

	if m.OnCancel != nil {

		if err := m.OnCancel.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("OnCancel")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("OnCancel")
			}
			return err
		}
	}

	return nil
}

func (m *WorkflowStatusDetail) contextValidateOnExit(ctx context.Context, formats strfmt.Registry) error {

	if m.OnExit != nil {

		if err := m.OnExit.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("OnExit")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("OnExit")
			}
			return err
		}
	}

	return nil
}

func (m *WorkflowStatusDetail) contextValidateOnFailure(ctx context.Context, formats strfmt.Registry) error {

	if m.OnFailure != nil {

		if err := m.OnFailure.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("OnFailure")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("OnFailure")
			}
			return err
		}
	}

	return nil
}

func (m *WorkflowStatusDetail) contextValidateOnSuccess(ctx context.Context, formats strfmt.Registry) error {

	if m.OnSuccess != nil {

		if err := m.OnSuccess.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("OnSuccess")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("OnSuccess")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WorkflowStatusDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkflowStatusDetail) UnmarshalBinary(b []byte) error {
	var res WorkflowStatusDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
