// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/yohamta/dagu/service/frontend/models"
)

// GetWorkflowDetailOKCode is the HTTP code returned for type GetWorkflowDetailOK
const GetWorkflowDetailOKCode int = 200

/*
GetWorkflowDetailOK A successful response.

swagger:response getWorkflowDetailOK
*/
type GetWorkflowDetailOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetWorkflowDetailResponse `json:"body,omitempty"`
}

// NewGetWorkflowDetailOK creates GetWorkflowDetailOK with default headers values
func NewGetWorkflowDetailOK() *GetWorkflowDetailOK {

	return &GetWorkflowDetailOK{}
}

// WithPayload adds the payload to the get workflow detail o k response
func (o *GetWorkflowDetailOK) WithPayload(payload *models.GetWorkflowDetailResponse) *GetWorkflowDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get workflow detail o k response
func (o *GetWorkflowDetailOK) SetPayload(payload *models.GetWorkflowDetailResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWorkflowDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetWorkflowDetailDefault Generic error response.

swagger:response getWorkflowDetailDefault
*/
type GetWorkflowDetailDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetWorkflowDetailDefault creates GetWorkflowDetailDefault with default headers values
func NewGetWorkflowDetailDefault(code int) *GetWorkflowDetailDefault {
	if code <= 0 {
		code = 500
	}

	return &GetWorkflowDetailDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get workflow detail default response
func (o *GetWorkflowDetailDefault) WithStatusCode(code int) *GetWorkflowDetailDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get workflow detail default response
func (o *GetWorkflowDetailDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get workflow detail default response
func (o *GetWorkflowDetailDefault) WithPayload(payload *models.APIError) *GetWorkflowDetailDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get workflow detail default response
func (o *GetWorkflowDetailDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWorkflowDetailDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
