// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// GetDagDetailsURL generates an URL for the get dag details operation
type GetDagDetailsURL struct {
	DagID string

	File *string
	Step *string
	Tab  *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetDagDetailsURL) WithBasePath(bp string) *GetDagDetailsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetDagDetailsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetDagDetailsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/dags/{dagId}"

	dagID := o.DagID
	if dagID != "" {
		_path = strings.Replace(_path, "{dagId}", dagID, -1)
	} else {
		return nil, errors.New("dagId is required on GetDagDetailsURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var fileQ string
	if o.File != nil {
		fileQ = *o.File
	}
	if fileQ != "" {
		qs.Set("file", fileQ)
	}

	var stepQ string
	if o.Step != nil {
		stepQ = *o.Step
	}
	if stepQ != "" {
		qs.Set("step", stepQ)
	}

	var tabQ string
	if o.Tab != nil {
		tabQ = *o.Tab
	}
	if tabQ != "" {
		qs.Set("tab", tabQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetDagDetailsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetDagDetailsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetDagDetailsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetDagDetailsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetDagDetailsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetDagDetailsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
