// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostWorkflowActionHandlerFunc turns a function with the right signature into a post workflow action handler
type PostWorkflowActionHandlerFunc func(PostWorkflowActionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostWorkflowActionHandlerFunc) Handle(params PostWorkflowActionParams) middleware.Responder {
	return fn(params)
}

// PostWorkflowActionHandler interface for that can handle valid post workflow action params
type PostWorkflowActionHandler interface {
	Handle(PostWorkflowActionParams) middleware.Responder
}

// NewPostWorkflowAction creates a new http.Handler for the post workflow action operation
func NewPostWorkflowAction(ctx *middleware.Context, handler PostWorkflowActionHandler) *PostWorkflowAction {
	return &PostWorkflowAction{Context: ctx, Handler: handler}
}

/*
	PostWorkflowAction swagger:route POST /workflows/{workflowId} postWorkflowAction

PostWorkflowAction post workflow action API
*/
type PostWorkflowAction struct {
	Context *middleware.Context
	Handler PostWorkflowActionHandler
}

func (o *PostWorkflowAction) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostWorkflowActionParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
