// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/coordinator/v1/coordinator.proto

package coordinatorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED Operation = 0
	Operation_OPERATION_START       Operation = 1 // Start a new DAG run
	Operation_OPERATION_RETRY       Operation = 2 // Retry an existing run
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_START",
		2: "OPERATION_RETRY",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_START":       1,
		"OPERATION_RETRY":       2,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_coordinator_v1_coordinator_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_proto_coordinator_v1_coordinator_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

// Request message for polling a task.
type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	PollerId      string                 `protobuf:"bytes,2,opt,name=poller_id,json=pollerId,proto3" json:"poller_id,omitempty"`                                                       // Unique ID for this poll request
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Worker labels for task matching
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *PollRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *PollRequest) GetPollerId() string {
	if x != nil {
		return x.PollerId
	}
	return ""
}

func (x *PollRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Response message for polling a task.
type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"` // The task to process.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *PollResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// Request message for dispatching a task.
type DispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *DispatchRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// Response message for dispatching a task.
type DispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{3}
}

// Task to process.
type Task struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Operation        Operation              `protobuf:"varint,6,opt,name=operation,proto3,enum=coordinator.v1.Operation" json:"operation,omitempty"`
	RootDagRunName   string                 `protobuf:"bytes,1,opt,name=root_dag_run_name,json=rootDagRunName,proto3" json:"root_dag_run_name,omitempty"`
	RootDagRunId     string                 `protobuf:"bytes,2,opt,name=root_dag_run_id,json=rootDagRunId,proto3" json:"root_dag_run_id,omitempty"`
	ParentDagRunName string                 `protobuf:"bytes,3,opt,name=parent_dag_run_name,json=parentDagRunName,proto3" json:"parent_dag_run_name,omitempty"`
	ParentDagRunId   string                 `protobuf:"bytes,4,opt,name=parent_dag_run_id,json=parentDagRunId,proto3" json:"parent_dag_run_id,omitempty"`
	DagRunId         string                 `protobuf:"bytes,5,opt,name=dag_run_id,json=dagRunId,proto3" json:"dag_run_id,omitempty"`
	Target           string                 `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`                                                                                                                  // DAG name or path
	Params           string                 `protobuf:"bytes,8,opt,name=params,proto3" json:"params,omitempty"`                                                                                                                  // Optional: parameters
	Step             string                 `protobuf:"bytes,9,opt,name=step,proto3" json:"step,omitempty"`                                                                                                                      // Optional: specific step (for RETRY)
	WorkerSelector   map[string]string      `protobuf:"bytes,10,rep,name=worker_selector,json=workerSelector,proto3" json:"worker_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Required worker labels for execution
	Definition       string                 `protobuf:"bytes,11,opt,name=definition,proto3" json:"definition,omitempty"`                                                                                                         // Optional: DAG definition (YAML) for local DAGs
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_v1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *Task) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *Task) GetRootDagRunName() string {
	if x != nil {
		return x.RootDagRunName
	}
	return ""
}

func (x *Task) GetRootDagRunId() string {
	if x != nil {
		return x.RootDagRunId
	}
	return ""
}

func (x *Task) GetParentDagRunName() string {
	if x != nil {
		return x.ParentDagRunName
	}
	return ""
}

func (x *Task) GetParentDagRunId() string {
	if x != nil {
		return x.ParentDagRunId
	}
	return ""
}

func (x *Task) GetDagRunId() string {
	if x != nil {
		return x.DagRunId
	}
	return ""
}

func (x *Task) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Task) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *Task) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *Task) GetWorkerSelector() map[string]string {
	if x != nil {
		return x.WorkerSelector
	}
	return nil
}

func (x *Task) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

var File_proto_coordinator_v1_coordinator_proto protoreflect.FileDescriptor

const file_proto_coordinator_v1_coordinator_proto_rawDesc = "" +
	"\n" +
	"&proto/coordinator/v1/coordinator.proto\x12\x0ecoordinator.v1\"\xc3\x01\n" +
	"\vPollRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tpoller_id\x18\x02 \x01(\tR\bpollerId\x12?\n" +
	"\x06labels\x18\x03 \x03(\v2'.coordinator.v1.PollRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\fPollResponse\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.coordinator.v1.TaskR\x04task\";\n" +
	"\x0fDispatchRequest\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.coordinator.v1.TaskR\x04task\"\x12\n" +
	"\x10DispatchResponse\"\x83\x04\n" +
	"\x04Task\x127\n" +
	"\toperation\x18\x06 \x01(\x0e2\x19.coordinator.v1.OperationR\toperation\x12)\n" +
	"\x11root_dag_run_name\x18\x01 \x01(\tR\x0erootDagRunName\x12%\n" +
	"\x0froot_dag_run_id\x18\x02 \x01(\tR\frootDagRunId\x12-\n" +
	"\x13parent_dag_run_name\x18\x03 \x01(\tR\x10parentDagRunName\x12)\n" +
	"\x11parent_dag_run_id\x18\x04 \x01(\tR\x0eparentDagRunId\x12\x1c\n" +
	"\n" +
	"dag_run_id\x18\x05 \x01(\tR\bdagRunId\x12\x16\n" +
	"\x06target\x18\a \x01(\tR\x06target\x12\x16\n" +
	"\x06params\x18\b \x01(\tR\x06params\x12\x12\n" +
	"\x04step\x18\t \x01(\tR\x04step\x12Q\n" +
	"\x0fworker_selector\x18\n" +
	" \x03(\v2(.coordinator.v1.Task.WorkerSelectorEntryR\x0eworkerSelector\x12\x1e\n" +
	"\n" +
	"definition\x18\v \x01(\tR\n" +
	"definition\x1aA\n" +
	"\x13WorkerSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*P\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOPERATION_START\x10\x01\x12\x13\n" +
	"\x0fOPERATION_RETRY\x10\x022\xa6\x01\n" +
	"\x12CoordinatorService\x12A\n" +
	"\x04Poll\x12\x1b.coordinator.v1.PollRequest\x1a\x1c.coordinator.v1.PollResponse\x12M\n" +
	"\bDispatch\x12\x1f.coordinator.v1.DispatchRequest\x1a .coordinator.v1.DispatchResponseB=Z;github.com/dagu-org/dagu/proto/coordinator/v1;coordinatorv1b\x06proto3"

var (
	file_proto_coordinator_v1_coordinator_proto_rawDescOnce sync.Once
	file_proto_coordinator_v1_coordinator_proto_rawDescData []byte
)

func file_proto_coordinator_v1_coordinator_proto_rawDescGZIP() []byte {
	file_proto_coordinator_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_proto_coordinator_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coordinator_v1_coordinator_proto_rawDesc), len(file_proto_coordinator_v1_coordinator_proto_rawDesc)))
	})
	return file_proto_coordinator_v1_coordinator_proto_rawDescData
}

var file_proto_coordinator_v1_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_coordinator_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_coordinator_v1_coordinator_proto_goTypes = []any{
	(Operation)(0),           // 0: coordinator.v1.Operation
	(*PollRequest)(nil),      // 1: coordinator.v1.PollRequest
	(*PollResponse)(nil),     // 2: coordinator.v1.PollResponse
	(*DispatchRequest)(nil),  // 3: coordinator.v1.DispatchRequest
	(*DispatchResponse)(nil), // 4: coordinator.v1.DispatchResponse
	(*Task)(nil),             // 5: coordinator.v1.Task
	nil,                      // 6: coordinator.v1.PollRequest.LabelsEntry
	nil,                      // 7: coordinator.v1.Task.WorkerSelectorEntry
}
var file_proto_coordinator_v1_coordinator_proto_depIdxs = []int32{
	6, // 0: coordinator.v1.PollRequest.labels:type_name -> coordinator.v1.PollRequest.LabelsEntry
	5, // 1: coordinator.v1.PollResponse.task:type_name -> coordinator.v1.Task
	5, // 2: coordinator.v1.DispatchRequest.task:type_name -> coordinator.v1.Task
	0, // 3: coordinator.v1.Task.operation:type_name -> coordinator.v1.Operation
	7, // 4: coordinator.v1.Task.worker_selector:type_name -> coordinator.v1.Task.WorkerSelectorEntry
	1, // 5: coordinator.v1.CoordinatorService.Poll:input_type -> coordinator.v1.PollRequest
	3, // 6: coordinator.v1.CoordinatorService.Dispatch:input_type -> coordinator.v1.DispatchRequest
	2, // 7: coordinator.v1.CoordinatorService.Poll:output_type -> coordinator.v1.PollResponse
	4, // 8: coordinator.v1.CoordinatorService.Dispatch:output_type -> coordinator.v1.DispatchResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_coordinator_v1_coordinator_proto_init() }
func file_proto_coordinator_v1_coordinator_proto_init() {
	if File_proto_coordinator_v1_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coordinator_v1_coordinator_proto_rawDesc), len(file_proto_coordinator_v1_coordinator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coordinator_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_proto_coordinator_v1_coordinator_proto_depIdxs,
		EnumInfos:         file_proto_coordinator_v1_coordinator_proto_enumTypes,
		MessageInfos:      file_proto_coordinator_v1_coordinator_proto_msgTypes,
	}.Build()
	File_proto_coordinator_v1_coordinator_proto = out.File
	file_proto_coordinator_v1_coordinator_proto_goTypes = nil
	file_proto_coordinator_v1_coordinator_proto_depIdxs = nil
}
