// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/internal/workerservice/v1/workerservice.proto

package workerservicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for polling a task.
type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_proto_internal_workerservice_v1_workerservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_workerservice_v1_workerservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_proto_internal_workerservice_v1_workerservice_proto_rawDescGZIP(), []int{0}
}

func (x *PollRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// Response message for polling a task.
type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"` // The task to process.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_proto_internal_workerservice_v1_workerservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_workerservice_v1_workerservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_proto_internal_workerservice_v1_workerservice_proto_rawDescGZIP(), []int{1}
}

func (x *PollResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// Task to process.
type Task struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RootDagRunName   string                 `protobuf:"bytes,1,opt,name=root_dag_run_name,json=rootDagRunName,proto3" json:"root_dag_run_name,omitempty"`
	RootDagRunId     string                 `protobuf:"bytes,2,opt,name=root_dag_run_id,json=rootDagRunId,proto3" json:"root_dag_run_id,omitempty"`
	ParentDagRunName string                 `protobuf:"bytes,3,opt,name=parent_dag_run_name,json=parentDagRunName,proto3" json:"parent_dag_run_name,omitempty"`
	ParentDagRunId   string                 `protobuf:"bytes,4,opt,name=parent_dag_run_id,json=parentDagRunId,proto3" json:"parent_dag_run_id,omitempty"`
	DagRunId         string                 `protobuf:"bytes,5,opt,name=dag_run_id,json=dagRunId,proto3" json:"dag_run_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_internal_workerservice_v1_workerservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_workerservice_v1_workerservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_internal_workerservice_v1_workerservice_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetRootDagRunName() string {
	if x != nil {
		return x.RootDagRunName
	}
	return ""
}

func (x *Task) GetRootDagRunId() string {
	if x != nil {
		return x.RootDagRunId
	}
	return ""
}

func (x *Task) GetParentDagRunName() string {
	if x != nil {
		return x.ParentDagRunName
	}
	return ""
}

func (x *Task) GetParentDagRunId() string {
	if x != nil {
		return x.ParentDagRunId
	}
	return ""
}

func (x *Task) GetDagRunId() string {
	if x != nil {
		return x.DagRunId
	}
	return ""
}

var File_proto_internal_workerservice_v1_workerservice_proto protoreflect.FileDescriptor

const file_proto_internal_workerservice_v1_workerservice_proto_rawDesc = "" +
	"\n" +
	"3proto/internal/workerservice/v1/workerservice.proto\x12\x10workerservice.v1\"*\n" +
	"\vPollRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\":\n" +
	"\fPollResponse\x12*\n" +
	"\x04task\x18\x01 \x01(\v2\x16.workerservice.v1.TaskR\x04task\"\xd0\x01\n" +
	"\x04Task\x12)\n" +
	"\x11root_dag_run_name\x18\x01 \x01(\tR\x0erootDagRunName\x12%\n" +
	"\x0froot_dag_run_id\x18\x02 \x01(\tR\frootDagRunId\x12-\n" +
	"\x13parent_dag_run_name\x18\x03 \x01(\tR\x10parentDagRunName\x12)\n" +
	"\x11parent_dag_run_id\x18\x04 \x01(\tR\x0eparentDagRunId\x12\x1c\n" +
	"\n" +
	"dag_run_id\x18\x05 \x01(\tR\bdagRunId2V\n" +
	"\rWorkerService\x12E\n" +
	"\x04Poll\x12\x1d.workerservice.v1.PollRequest\x1a\x1e.workerservice.v1.PollResponseBAZ?github.com/dagu-org/dagu/proto/workerservice/v1;workerservicev1b\x06proto3"

var (
	file_proto_internal_workerservice_v1_workerservice_proto_rawDescOnce sync.Once
	file_proto_internal_workerservice_v1_workerservice_proto_rawDescData []byte
)

func file_proto_internal_workerservice_v1_workerservice_proto_rawDescGZIP() []byte {
	file_proto_internal_workerservice_v1_workerservice_proto_rawDescOnce.Do(func() {
		file_proto_internal_workerservice_v1_workerservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_internal_workerservice_v1_workerservice_proto_rawDesc), len(file_proto_internal_workerservice_v1_workerservice_proto_rawDesc)))
	})
	return file_proto_internal_workerservice_v1_workerservice_proto_rawDescData
}

var file_proto_internal_workerservice_v1_workerservice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_internal_workerservice_v1_workerservice_proto_goTypes = []any{
	(*PollRequest)(nil),  // 0: workerservice.v1.PollRequest
	(*PollResponse)(nil), // 1: workerservice.v1.PollResponse
	(*Task)(nil),         // 2: workerservice.v1.Task
}
var file_proto_internal_workerservice_v1_workerservice_proto_depIdxs = []int32{
	2, // 0: workerservice.v1.PollResponse.task:type_name -> workerservice.v1.Task
	0, // 1: workerservice.v1.WorkerService.Poll:input_type -> workerservice.v1.PollRequest
	1, // 2: workerservice.v1.WorkerService.Poll:output_type -> workerservice.v1.PollResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_internal_workerservice_v1_workerservice_proto_init() }
func file_proto_internal_workerservice_v1_workerservice_proto_init() {
	if File_proto_internal_workerservice_v1_workerservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_internal_workerservice_v1_workerservice_proto_rawDesc), len(file_proto_internal_workerservice_v1_workerservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_internal_workerservice_v1_workerservice_proto_goTypes,
		DependencyIndexes: file_proto_internal_workerservice_v1_workerservice_proto_depIdxs,
		MessageInfos:      file_proto_internal_workerservice_v1_workerservice_proto_msgTypes,
	}.Build()
	File_proto_internal_workerservice_v1_workerservice_proto = out.File
	file_proto_internal_workerservice_v1_workerservice_proto_goTypes = nil
	file_proto_internal_workerservice_v1_workerservice_proto_depIdxs = nil
}
