// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	ApiTokenScopes  = "apiToken.Scopes"
	BasicAuthScopes = "basicAuth.Scopes"
)

// Defines values for DAGAction.
const (
	DAGActionMarkFailed  DAGAction = "mark-failed"
	DAGActionMarkSuccess DAGAction = "mark-success"
	DAGActionRename      DAGAction = "rename"
	DAGActionRetry       DAGAction = "retry"
	DAGActionSave        DAGAction = "save"
	DAGActionStart       DAGAction = "start"
	DAGActionStop        DAGAction = "stop"
	DAGActionSuspend     DAGAction = "suspend"
)

// Defines values for DAGDetailTab.
const (
	DAGDetailTabHistory      DAGDetailTab = "history"
	DAGDetailTabLog          DAGDetailTab = "log"
	DAGDetailTabSchedulerLog DAGDetailTab = "scheduler-log"
	DAGDetailTabSpec         DAGDetailTab = "spec"
	DAGDetailTabStatus       DAGDetailTab = "status"
)

// Defines values for ErrorCode.
const (
	ErrorCodeAlreadyExists   ErrorCode = "already_exists"
	ErrorCodeAlreadyRunning  ErrorCode = "already_running"
	ErrorCodeBadGateway      ErrorCode = "bad_gateway"
	ErrorCodeBadRequest      ErrorCode = "bad_request"
	ErrorCodeInternalError   ErrorCode = "internal_error"
	ErrorCodeNotFound        ErrorCode = "not_found"
	ErrorCodeNotRunning      ErrorCode = "not_running"
	ErrorCodeRemoteNodeError ErrorCode = "remote_node_error"
	ErrorCodeUnauthorized    ErrorCode = "unauthorized"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusHealthy   HealthResponseStatus = "healthy"
	HealthResponseStatusUnhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for NodeStatus.
const (
	NodeStatusN0 NodeStatus = 0
	NodeStatusN1 NodeStatus = 1
	NodeStatusN2 NodeStatus = 2
	NodeStatusN3 NodeStatus = 3
	NodeStatusN4 NodeStatus = 4
	NodeStatusN5 NodeStatus = 5
)

// Defines values for NodeStatusText.
const (
	NodeStatusTextCanceled   NodeStatusText = "canceled"
	NodeStatusTextFailed     NodeStatusText = "failed"
	NodeStatusTextFinished   NodeStatusText = "finished"
	NodeStatusTextNotStarted NodeStatusText = "not started"
	NodeStatusTextRunning    NodeStatusText = "running"
	NodeStatusTextSkipped    NodeStatusText = "skipped"
)

// Defines values for Status.
const (
	StatusN0 Status = 0
	StatusN1 Status = 1
	StatusN2 Status = 2
	StatusN3 Status = 3
	StatusN4 Status = 4
)

// Defines values for StatusText.
const (
	StatusTextCancelled  StatusText = "cancelled"
	StatusTextFailed     StatusText = "failed"
	StatusTextFinished   StatusText = "finished"
	StatusTextNotStarted StatusText = "not started"
	StatusTextRunning    StatusText = "running"
)

// DAG Core DAG configuration containing workflow definition and metadata
type DAG struct {
	// DefaultParams Default parameter values in JSON format if not specified at runtime
	DefaultParams *string `json:"DefaultParams,omitempty"`

	// Description Human-readable description of the DAG's purpose and behavior
	Description *string `json:"Description,omitempty"`

	// Group Logical grouping of related DAGs for organizational purposes
	Group *string `json:"Group,omitempty"`

	// Name Unique identifier for the DAG within its group
	Name string `json:"Name"`

	// Params List of parameter names that can be passed to the DAG at runtime
	Params *[]string `json:"Params,omitempty"`

	// Schedule List of scheduling expressions defining when the DAG should run
	Schedule *[]Schedule `json:"Schedule,omitempty"`

	// Tags List of tags for categorizing and filtering DAGs
	Tags *[]string `json:"Tags,omitempty"`
}

// DAGAction Action to be performed on the DAG. Possible values include:
// - start: Start the DAG
// - suspend: Suspend the DAG
// - stop: Stop the DAG
// - retry: Retry the last run
// - mark-success: Mark the last run as successful
// - mark-failed: Mark the last run as failed
// - save: Save the current state of the DAG
// - rename: Rename the DAG
type DAGAction string

// DAGDetailTab Indicates which part of the DAG to retrieve
type DAGDetailTab string

// DAGDetails Detailed DAG configuration information
type DAGDetails struct {
	// DefaultParams Default parameter values in JSON format if not specified at runtime
	DefaultParams *string `json:"DefaultParams,omitempty"`

	// Delay Time in seconds to wait before starting the DAG
	Delay *int `json:"Delay,omitempty"`

	// Description Human-readable description of the DAG's purpose and behavior
	Description *string `json:"Description,omitempty"`

	// Env List of environment variables to set before executing
	Env *[]string `json:"Env,omitempty"`

	// Group Logical grouping of related DAGs for organizational purposes
	Group *string `json:"Group,omitempty"`

	// HandlerOn Configuration for event handlers in a DAG
	HandlerOn *HandlerOn `json:"HandlerOn,omitempty"`

	// HistRetentionDays Number of days to retain historical logs
	HistRetentionDays *int `json:"HistRetentionDays,omitempty"`

	// Location Path to the DAG file
	Location *string `json:"Location,omitempty"`

	// LogDir Directory path for storing log files
	LogDir *string `json:"LogDir,omitempty"`

	// MaxActiveRuns Maximum number of concurrent steps to run
	MaxActiveRuns *int `json:"MaxActiveRuns,omitempty"`

	// Name Unique identifier for the DAG within its group
	Name string `json:"Name"`

	// Params List of parameter names that can be passed to the DAG at runtime
	Params *[]string `json:"Params,omitempty"`

	// Preconditions Conditions that must be met before the DAG can start
	Preconditions *[]Precondition `json:"Preconditions,omitempty"`

	// Schedule List of scheduling expressions defining when the DAG should run
	Schedule *[]Schedule `json:"Schedule,omitempty"`

	// Steps List of steps to execute in the DAG
	Steps *[]Step `json:"Steps,omitempty"`

	// Tags List of tags for categorizing and filtering DAGs
	Tags *[]string `json:"Tags,omitempty"`
}

// DAGFile DAG file with its status information
type DAGFile struct {
	// DAG Core DAG configuration containing workflow definition and metadata
	DAG DAG `json:"DAG"`

	// Error Error message if any
	Error *string `json:"Error,omitempty"`

	// File Path to the DAG file
	File string `json:"File"`

	// Status Current status of a DAG run
	Status StatusDetails `json:"Status"`

	// Suspended Whether the DAG is suspended
	Suspended bool `json:"Suspended"`
}

// DAGHistoryData Historical run data for a DAG
type DAGHistoryData struct {
	// GridData Grid data for visualization
	GridData []DAGLogGridItem `json:"GridData"`

	// StatusDetails Detailed status information for each run
	StatusDetails []DAGStatusDetails `json:"StatusDetails"`
}

// DAGLogGridItem Grid item for log visualization
type DAGLogGridItem struct {
	// History Status of the step ordered by time
	History []NodeStatus `json:"History"`

	// Name Name of the step
	Name string `json:"Name"`
}

// DAGName Name of the DAG, must be unique
type DAGName = string

// DAGStatusDetails Detailed status of a DAG run including child nodes
type DAGStatusDetails struct {
	// FinishedAt RFC3339 timestamp when the DAG run finished
	FinishedAt string `json:"FinishedAt"`

	// Log Path to the log file
	Log string `json:"Log"`

	// Name Name of the DAG
	Name string `json:"Name"`

	// Nodes Status of individual steps within the DAG
	Nodes []Node `json:"Nodes"`

	// OnCancel Status of an individual step within a DAG run
	OnCancel *Node `json:"OnCancel,omitempty"`

	// OnExit Status of an individual step within a DAG run
	OnExit *Node `json:"OnExit,omitempty"`

	// OnFailure Status of an individual step within a DAG run
	OnFailure *Node `json:"OnFailure,omitempty"`

	// OnSuccess Status of an individual step within a DAG run
	OnSuccess *Node `json:"OnSuccess,omitempty"`

	// Params Parameters in JSON format
	Params *string `json:"Params,omitempty"`

	// Pid Process ID of the DAG run
	Pid int `json:"Pid"`

	// RequestId Unique identifier for the run request
	RequestId string `json:"RequestId"`

	// StartedAt RFC3339 timestamp when the DAG run started
	StartedAt string `json:"StartedAt"`

	// Status Numeric status code indicating current run state:
	// 0: "Not started"
	// 1: "Running"
	// 2: "Failed"
	// 3: "Cancelled"
	// 4: "Success"
	Status Status `json:"Status"`

	// StatusText Human-readable status description for the DAG run
	StatusText StatusText `json:"StatusText"`
}

// DAGStatusFileDetails Detailed status information for a DAG instance
type DAGStatusFileDetails struct {
	// DAG Detailed DAG configuration information
	DAG DAGDetails `json:"DAG"`

	// Error Error message if any
	Error *string `json:"Error,omitempty"`

	// File Path to the DAG file
	File string `json:"File"`

	// Status Detailed status of a DAG run including child nodes
	Status DAGStatusDetails `json:"Status"`

	// Suspended Whether the DAG is suspended
	Suspended bool `json:"Suspended"`
}

// Error Generic error response object
type Error struct {
	// Code Error code indicating the type of error
	Code ErrorCode `json:"code"`

	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Short error message
	Message string `json:"message"`
}

// ErrorCode Error code indicating the type of error
type ErrorCode string

// HandlerOn Configuration for event handlers in a DAG
type HandlerOn struct {
	// Cancel Individual task within a DAG that performs a specific operation
	Cancel *Step `json:"Cancel,omitempty"`

	// Exit Individual task within a DAG that performs a specific operation
	Exit *Step `json:"Exit,omitempty"`

	// Failure Individual task within a DAG that performs a specific operation
	Failure *Step `json:"Failure,omitempty"`

	// Success Individual task within a DAG that performs a specific operation
	Success *Step `json:"Success,omitempty"`
}

// HealthResponse Response object for the health check endpoint
type HealthResponse struct {
	// Status Overall health status of the server
	Status HealthResponseStatus `json:"status"`

	// Timestamp Current server time
	Timestamp string `json:"timestamp"`

	// Uptime Server uptime in seconds
	Uptime int `json:"uptime"`

	// Version Current version of the server
	Version string `json:"version"`
}

// HealthResponseStatus Overall health status of the server
type HealthResponseStatus string

// ListTagResponse Response object for listing all tags
type ListTagResponse struct {
	// Errors List of errors encountered during the request
	Errors []string `json:"Errors"`

	// Tags List of unique tags
	Tags []string `json:"Tags"`
}

// Node Status of an individual step within a DAG run
type Node struct {
	// DoneCount Number of successful completions for repeating steps
	DoneCount int `json:"DoneCount"`

	// Error Error message if the step failed
	Error *string `json:"Error,omitempty"`

	// FinishedAt RFC3339 timestamp when the step finished
	FinishedAt string `json:"FinishedAt"`

	// Log Path to step-specific log file
	Log string `json:"Log"`

	// RetryCount Number of retry attempts made for this step
	RetryCount int `json:"RetryCount"`

	// StartedAt RFC3339 timestamp when the step started
	StartedAt string `json:"StartedAt"`

	// Status Numeric status code indicating current node state:
	// 0: "Not started"
	// 1: "Running"
	// 2: "Failed"
	// 3: "Cancelled"
	// 4: "Success"
	// 5: "Skipped"
	Status NodeStatus `json:"Status"`

	// StatusText Human-readable status description for the node
	StatusText NodeStatusText `json:"StatusText"`

	// Step Individual task within a DAG that performs a specific operation
	Step Step `json:"Step"`
}

// NodeStatus Numeric status code indicating current node state:
// 0: "Not started"
// 1: "Running"
// 2: "Failed"
// 3: "Cancelled"
// 4: "Success"
// 5: "Skipped"
type NodeStatus int

// NodeStatusText Human-readable status description for the node
type NodeStatusText string

// Pagination defines model for Pagination.
type Pagination struct {
	// CurrentPage current page number
	CurrentPage int `json:"currentPage"`

	// NextPage next page number
	NextPage int `json:"nextPage"`

	// PrevPage previous page number
	PrevPage int `json:"prevPage"`

	// TotalPages total number of pages
	TotalPages int `json:"totalPages"`

	// TotalRecords total number of records
	TotalRecords int `json:"totalRecords"`
}

// PostDAGActionResponse Response object for posting an action to a DAG
type PostDAGActionResponse struct {
	// NewName New DAG name, if the action resulted in a new DAG
	NewName *string `json:"NewName,omitempty"`
}

// Precondition Precondition that must be satisfied before running a step or DAG
type Precondition struct {
	// Condition Expression or check to evaluate
	Condition *string `json:"Condition,omitempty"`

	// Expected Expected result of the condition evaluation
	Expected *string `json:"Expected,omitempty"`
}

// RepeatPolicy Configuration for step retry behavior
type RepeatPolicy struct {
	// Interval Time in seconds to wait between retry attempts
	Interval *int `json:"Interval,omitempty"`

	// Repeat Whether the step should be retried on failure
	Repeat *bool `json:"Repeat,omitempty"`
}

// Schedule Schedule configuration for DAG run
type Schedule struct {
	// Expression Cron expression or schedule pattern
	Expression string `json:"Expression"`
}

// SchedulerLog Log information for the scheduler
type SchedulerLog struct {
	// Content Log content
	Content string `json:"Content"`

	// LogFile Path to the scheduler log file
	LogFile string `json:"LogFile"`
}

// SearchDAGsMatchItem Details of a search match within a DAG
type SearchDAGsMatchItem struct {
	// Line Matching line content
	Line string `json:"Line"`

	// LineNumber Line number where match was found
	LineNumber int `json:"LineNumber"`

	// StartLine Start line for context
	StartLine int `json:"StartLine"`
}

// SearchDAGsResultItem Individual search result item for a DAG
type SearchDAGsResultItem struct {
	// DAG Core DAG configuration containing workflow definition and metadata
	DAG DAG `json:"DAG"`

	// Matches Details of where matches were found
	Matches []SearchDAGsMatchItem `json:"Matches"`

	// Name Name of the matching DAG
	Name string `json:"Name"`
}

// Status Numeric status code indicating current run state:
// 0: "Not started"
// 1: "Running"
// 2: "Failed"
// 3: "Cancelled"
// 4: "Success"
type Status int

// StatusDetails Current status of a DAG run
type StatusDetails struct {
	// FinishedAt RFC 3339 timestamp when the DAG run finished
	FinishedAt string `json:"FinishedAt"`

	// Log Path to the log file
	Log *string `json:"Log,omitempty"`

	// Name Name of the DAG being executed
	Name string `json:"Name"`

	// Params Runtime parameters passed to the DAG in JSON format
	Params *string `json:"Params,omitempty"`

	// Pid Process ID of the DAG run
	Pid *int `json:"Pid,omitempty"`

	// RequestId Unique identifier for the DAG run request
	RequestId string `json:"RequestId"`

	// StartedAt RFC 3339 timestamp when the DAG run started
	StartedAt string `json:"StartedAt"`

	// Status Numeric status code indicating current run state:
	// 0: "Not started"
	// 1: "Running"
	// 2: "Failed"
	// 3: "Cancelled"
	// 4: "Success"
	Status Status `json:"Status"`

	// StatusText Human-readable status description for the DAG run
	StatusText StatusText `json:"StatusText"`
}

// StatusText Human-readable status description for the DAG run
type StatusText string

// Step Individual task within a DAG that performs a specific operation
type Step struct {
	// Args List of arguments to pass to the command
	Args *[]string `json:"Args,omitempty"`

	// CmdWithArgs Complete command string including arguments to execute
	CmdWithArgs *string `json:"CmdWithArgs,omitempty"`

	// Command Base command to execute without arguments
	Command *string `json:"Command,omitempty"`

	// Depends List of step names that must complete before this step can start
	Depends *[]string `json:"Depends,omitempty"`

	// Description Human-readable description of what the step does
	Description *string `json:"Description,omitempty"`

	// Dir Working directory for executing the step's command
	Dir *string `json:"Dir,omitempty"`

	// MailOnError Whether to send email notifications on step failure
	MailOnError *bool `json:"MailOnError,omitempty"`

	// Name Unique identifier for the step within the DAG
	Name string `json:"Name"`

	// Output Variable name to store the step's output
	Output *string `json:"Output,omitempty"`

	// Params Parameters to pass to the sub DAG in JSON format
	Params *string `json:"Params,omitempty"`

	// Preconditions Conditions that must be met before the step can start
	Preconditions *[]Precondition `json:"Preconditions,omitempty"`

	// RepeatPolicy Configuration for step retry behavior
	RepeatPolicy *RepeatPolicy `json:"RepeatPolicy,omitempty"`

	// Run Sub DAG to run
	Run *string `json:"Run,omitempty"`

	// Script Script content if the step executes a script file
	Script *string `json:"Script,omitempty"`

	// Stderr File path for capturing standard error
	Stderr *string `json:"Stderr,omitempty"`

	// Stdout File path for capturing standard output
	Stdout *string `json:"Stdout,omitempty"`
}

// StepLog Log information for a specific step
type StepLog struct {
	// Content Log content
	Content string `json:"Content"`

	// LogFile Path to the log file
	LogFile string `json:"LogFile"`

	// Step Status of an individual step within a DAG run
	Step Node `json:"Step"`
}

// Page defines model for Page.
type Page = int

// PerPage defines model for PerPage.
type PerPage = int

// ListDAGsParams defines parameters for ListDAGs.
type ListDAGsParams struct {
	// Page page number of items to fetch (default is 1)
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PerPage number of items per page (default is 30, max is 100)
	PerPage *PerPage `form:"perPage,omitempty" json:"perPage,omitempty"`

	// Name Filter DAGs by name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Tag Filter DAGs by tag
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// CreateDAGJSONBody defines parameters for CreateDAG.
type CreateDAGJSONBody struct {
	// Name Name of the DAG, must be unique
	Name DAGName `json:"name"`
}

// SearchDAGsParams defines parameters for SearchDAGs.
type SearchDAGsParams struct {
	// Q A search query string
	Q string `form:"q" json:"q"`
}

// GetDAGDetailsParams defines parameters for GetDAGDetails.
type GetDAGDetailsParams struct {
	// Tab Specific part of the DAG to retrieve
	Tab *DAGDetailTab `form:"tab,omitempty" json:"tab,omitempty"`

	// ReqId Specific file related to the DAG
	ReqId *string `form:"reqId,omitempty" json:"reqId,omitempty"`

	// Step Step name within the DAG
	Step *string `form:"step,omitempty" json:"step,omitempty"`
}

// PostDAGActionJSONBody defines parameters for PostDAGAction.
type PostDAGActionJSONBody struct {
	// Action Action to be performed on the DAG. Possible values include:
	// - start: Start the DAG
	// - suspend: Suspend the DAG
	// - stop: Stop the DAG
	// - retry: Retry the last run
	// - mark-success: Mark the last run as successful
	// - mark-failed: Mark the last run as failed
	// - save: Save the current state of the DAG
	// - rename: Rename the DAG
	Action DAGAction `json:"action"`

	// Params Additional parameters for the action in JSON format
	Params *string `json:"params,omitempty"`

	// RequestId Unique request ID for the action
	RequestId *string `json:"requestId,omitempty"`

	// Step Step name if the action targets a specific step
	Step *string `json:"step,omitempty"`

	// Value Optional extra value for the action
	Value *string `json:"value,omitempty"`
}

// UpdateDAGSpecJSONBody defines parameters for UpdateDAGSpec.
type UpdateDAGSpecJSONBody struct {
	// Spec The new DAG spec
	Spec string `json:"spec"`
}

// CreateDAGJSONRequestBody defines body for CreateDAG for application/json ContentType.
type CreateDAGJSONRequestBody CreateDAGJSONBody

// PostDAGActionJSONRequestBody defines body for PostDAGAction for application/json ContentType.
type PostDAGActionJSONRequestBody PostDAGActionJSONBody

// UpdateDAGSpecJSONRequestBody defines body for UpdateDAGSpec for application/json ContentType.
type UpdateDAGSpecJSONRequestBody UpdateDAGSpecJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List DAGs
	// (GET /dags)
	ListDAGs(w http.ResponseWriter, r *http.Request, params ListDAGsParams)
	// Create a new DAG
	// (POST /dags)
	CreateDAG(w http.ResponseWriter, r *http.Request)
	// Search DAGs
	// (GET /dags/search)
	SearchDAGs(w http.ResponseWriter, r *http.Request, params SearchDAGsParams)
	// List all tags
	// (GET /dags/tags)
	ListTags(w http.ResponseWriter, r *http.Request)
	// Delete a DAG
	// (DELETE /dags/{name})
	DeleteDAG(w http.ResponseWriter, r *http.Request, name string)
	// Get DAG details
	// (GET /dags/{name})
	GetDAGDetails(w http.ResponseWriter, r *http.Request, name string, params GetDAGDetailsParams)
	// Perform an action on a DAG
	// (POST /dags/{name})
	PostDAGAction(w http.ResponseWriter, r *http.Request, name string)
	// Get DAG Spec
	// (GET /dags/{name}/spec)
	GetDAGSpec(w http.ResponseWriter, r *http.Request, name DAGName)
	// Update DAG Spec
	// (PUT /dags/{name}/spec)
	UpdateDAGSpec(w http.ResponseWriter, r *http.Request, name DAGName)
	// Health check endpoint
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List DAGs
// (GET /dags)
func (_ Unimplemented) ListDAGs(w http.ResponseWriter, r *http.Request, params ListDAGsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new DAG
// (POST /dags)
func (_ Unimplemented) CreateDAG(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search DAGs
// (GET /dags/search)
func (_ Unimplemented) SearchDAGs(w http.ResponseWriter, r *http.Request, params SearchDAGsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all tags
// (GET /dags/tags)
func (_ Unimplemented) ListTags(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a DAG
// (DELETE /dags/{name})
func (_ Unimplemented) DeleteDAG(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get DAG details
// (GET /dags/{name})
func (_ Unimplemented) GetDAGDetails(w http.ResponseWriter, r *http.Request, name string, params GetDAGDetailsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Perform an action on a DAG
// (POST /dags/{name})
func (_ Unimplemented) PostDAGAction(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get DAG Spec
// (GET /dags/{name}/spec)
func (_ Unimplemented) GetDAGSpec(w http.ResponseWriter, r *http.Request, name DAGName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update DAG Spec
// (PUT /dags/{name}/spec)
func (_ Unimplemented) UpdateDAGSpec(w http.ResponseWriter, r *http.Request, name DAGName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check endpoint
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDAGs operation middleware
func (siw *ServerInterfaceWrapper) ListDAGs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDAGsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameter("form", true, false, "perPage", r.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", r.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDAGs(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDAG operation middleware
func (siw *ServerInterfaceWrapper) CreateDAG(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDAG(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchDAGs operation middleware
func (siw *ServerInterfaceWrapper) SearchDAGs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchDAGsParams

	// ------------- Required query parameter "q" -------------

	if paramValue := r.URL.Query().Get("q"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchDAGs(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTags operation middleware
func (siw *ServerInterfaceWrapper) ListTags(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTags(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDAG operation middleware
func (siw *ServerInterfaceWrapper) DeleteDAG(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDAG(w, r, name)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDAGDetails operation middleware
func (siw *ServerInterfaceWrapper) GetDAGDetails(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDAGDetailsParams

	// ------------- Optional query parameter "tab" -------------

	err = runtime.BindQueryParameter("form", true, false, "tab", r.URL.Query(), &params.Tab)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tab", Err: err})
		return
	}

	// ------------- Optional query parameter "reqId" -------------

	err = runtime.BindQueryParameter("form", true, false, "reqId", r.URL.Query(), &params.ReqId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reqId", Err: err})
		return
	}

	// ------------- Optional query parameter "step" -------------

	err = runtime.BindQueryParameter("form", true, false, "step", r.URL.Query(), &params.Step)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "step", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDAGDetails(w, r, name, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDAGAction operation middleware
func (siw *ServerInterfaceWrapper) PostDAGAction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDAGAction(w, r, name)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDAGSpec operation middleware
func (siw *ServerInterfaceWrapper) GetDAGSpec(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name DAGName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDAGSpec(w, r, name)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateDAGSpec operation middleware
func (siw *ServerInterfaceWrapper) UpdateDAGSpec(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name DAGName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDAGSpec(w, r, name)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dags", wrapper.ListDAGs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dags", wrapper.CreateDAG)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dags/search", wrapper.SearchDAGs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dags/tags", wrapper.ListTags)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/dags/{name}", wrapper.DeleteDAG)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dags/{name}", wrapper.GetDAGDetails)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dags/{name}", wrapper.PostDAGAction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dags/{name}/spec", wrapper.GetDAGSpec)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/dags/{name}/spec", wrapper.UpdateDAGSpec)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})

	return r
}

type ListDAGsRequestObject struct {
	Params ListDAGsParams
}

type ListDAGsResponseObject interface {
	VisitListDAGsResponse(w http.ResponseWriter) error
}

type ListDAGs200JSONResponse struct {
	// Dags List of DAGs with their status and metadata
	Dags []DAGFile `json:"dags"`

	// Errors List of errors encountered during the request
	Errors     []string   `json:"errors"`
	Pagination Pagination `json:"pagination"`
}

func (response ListDAGs200JSONResponse) VisitListDAGsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListDAGsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListDAGsdefaultJSONResponse) VisitListDAGsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateDAGRequestObject struct {
	Body *CreateDAGJSONRequestBody
}

type CreateDAGResponseObject interface {
	VisitCreateDAGResponse(w http.ResponseWriter) error
}

type CreateDAG201JSONResponse struct {
	// Name Name of the newly created DAG
	Name string `json:"name"`
}

func (response CreateDAG201JSONResponse) VisitCreateDAGResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDAGdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateDAGdefaultJSONResponse) VisitCreateDAGResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type SearchDAGsRequestObject struct {
	Params SearchDAGsParams
}

type SearchDAGsResponseObject interface {
	VisitSearchDAGsResponse(w http.ResponseWriter) error
}

type SearchDAGs200JSONResponse struct {
	// Errors Errors encountered during the search
	Errors []string `json:"Errors"`

	// Results Search results matching the query
	Results []SearchDAGsResultItem `json:"Results"`
}

func (response SearchDAGs200JSONResponse) VisitSearchDAGsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchDAGsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SearchDAGsdefaultJSONResponse) VisitSearchDAGsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListTagsRequestObject struct {
}

type ListTagsResponseObject interface {
	VisitListTagsResponse(w http.ResponseWriter) error
}

type ListTags200JSONResponse ListTagResponse

func (response ListTags200JSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTagsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListTagsdefaultJSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteDAGRequestObject struct {
	Name string `json:"name"`
}

type DeleteDAGResponseObject interface {
	VisitDeleteDAGResponse(w http.ResponseWriter) error
}

type DeleteDAG204Response struct {
}

func (response DeleteDAG204Response) VisitDeleteDAGResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDAG404JSONResponse Error

func (response DeleteDAG404JSONResponse) VisitDeleteDAGResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDAGdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteDAGdefaultJSONResponse) VisitDeleteDAGResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetDAGDetailsRequestObject struct {
	Name   string `json:"name"`
	Params GetDAGDetailsParams
}

type GetDAGDetailsResponseObject interface {
	VisitGetDAGDetailsResponse(w http.ResponseWriter) error
}

type GetDAGDetails200JSONResponse struct {
	// DAG Detailed status information for a DAG instance
	DAG DAGStatusFileDetails `json:"DAG"`

	// Definition DAG definition
	Definition *string `json:"Definition,omitempty"`

	// Errors List of errors encountered during the request
	Errors []string `json:"Errors"`

	// HistoryData Historical run data for a DAG
	HistoryData *DAGHistoryData `json:"HistoryData,omitempty"`

	// LogUrl URL to access logs directly
	LogUrl *string `json:"LogUrl,omitempty"`

	// ScLog Log information for the scheduler
	ScLog *SchedulerLog `json:"ScLog,omitempty"`

	// StepLog Log information for a specific step
	StepLog *StepLog `json:"StepLog,omitempty"`

	// Title Title of the Page
	Title string `json:"Title"`
}

func (response GetDAGDetails200JSONResponse) VisitGetDAGDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDAGDetailsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetDAGDetailsdefaultJSONResponse) VisitGetDAGDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostDAGActionRequestObject struct {
	Name string `json:"name"`
	Body *PostDAGActionJSONRequestBody
}

type PostDAGActionResponseObject interface {
	VisitPostDAGActionResponse(w http.ResponseWriter) error
}

type PostDAGAction200JSONResponse PostDAGActionResponse

func (response PostDAGAction200JSONResponse) VisitPostDAGActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostDAGActiondefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PostDAGActiondefaultJSONResponse) VisitPostDAGActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetDAGSpecRequestObject struct {
	Name DAGName `json:"name"`
}

type GetDAGSpecResponseObject interface {
	VisitGetDAGSpecResponse(w http.ResponseWriter) error
}

type GetDAGSpec200JSONResponse struct {
	// Errors List of errors in the spec
	Errors []string `json:"errors"`

	// Spec The DAG spec
	Spec string `json:"spec"`
}

func (response GetDAGSpec200JSONResponse) VisitGetDAGSpecResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDAGSpecdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetDAGSpecdefaultJSONResponse) VisitGetDAGSpecResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateDAGSpecRequestObject struct {
	Name DAGName `json:"name"`
	Body *UpdateDAGSpecJSONRequestBody
}

type UpdateDAGSpecResponseObject interface {
	VisitUpdateDAGSpecResponse(w http.ResponseWriter) error
}

type UpdateDAGSpec200Response struct {
}

func (response UpdateDAGSpec200Response) VisitUpdateDAGSpecResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateDAGSpec400JSONResponse struct {
	// Errors List of errors in the spec
	Errors []string `json:"errors"`
}

func (response UpdateDAGSpec400JSONResponse) VisitUpdateDAGSpecResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateDAGSpecdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdateDAGSpecdefaultJSONResponse) VisitUpdateDAGSpecResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthdefaultResponse struct {
	StatusCode int
}

func (response GetHealthdefaultResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List DAGs
	// (GET /dags)
	ListDAGs(ctx context.Context, request ListDAGsRequestObject) (ListDAGsResponseObject, error)
	// Create a new DAG
	// (POST /dags)
	CreateDAG(ctx context.Context, request CreateDAGRequestObject) (CreateDAGResponseObject, error)
	// Search DAGs
	// (GET /dags/search)
	SearchDAGs(ctx context.Context, request SearchDAGsRequestObject) (SearchDAGsResponseObject, error)
	// List all tags
	// (GET /dags/tags)
	ListTags(ctx context.Context, request ListTagsRequestObject) (ListTagsResponseObject, error)
	// Delete a DAG
	// (DELETE /dags/{name})
	DeleteDAG(ctx context.Context, request DeleteDAGRequestObject) (DeleteDAGResponseObject, error)
	// Get DAG details
	// (GET /dags/{name})
	GetDAGDetails(ctx context.Context, request GetDAGDetailsRequestObject) (GetDAGDetailsResponseObject, error)
	// Perform an action on a DAG
	// (POST /dags/{name})
	PostDAGAction(ctx context.Context, request PostDAGActionRequestObject) (PostDAGActionResponseObject, error)
	// Get DAG Spec
	// (GET /dags/{name}/spec)
	GetDAGSpec(ctx context.Context, request GetDAGSpecRequestObject) (GetDAGSpecResponseObject, error)
	// Update DAG Spec
	// (PUT /dags/{name}/spec)
	UpdateDAGSpec(ctx context.Context, request UpdateDAGSpecRequestObject) (UpdateDAGSpecResponseObject, error)
	// Health check endpoint
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListDAGs operation middleware
func (sh *strictHandler) ListDAGs(w http.ResponseWriter, r *http.Request, params ListDAGsParams) {
	var request ListDAGsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDAGs(ctx, request.(ListDAGsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDAGs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDAGsResponseObject); ok {
		if err := validResponse.VisitListDAGsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDAG operation middleware
func (sh *strictHandler) CreateDAG(w http.ResponseWriter, r *http.Request) {
	var request CreateDAGRequestObject

	var body CreateDAGJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDAG(ctx, request.(CreateDAGRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDAG")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDAGResponseObject); ok {
		if err := validResponse.VisitCreateDAGResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchDAGs operation middleware
func (sh *strictHandler) SearchDAGs(w http.ResponseWriter, r *http.Request, params SearchDAGsParams) {
	var request SearchDAGsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchDAGs(ctx, request.(SearchDAGsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchDAGs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchDAGsResponseObject); ok {
		if err := validResponse.VisitSearchDAGsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTags operation middleware
func (sh *strictHandler) ListTags(w http.ResponseWriter, r *http.Request) {
	var request ListTagsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTags(ctx, request.(ListTagsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTags")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTagsResponseObject); ok {
		if err := validResponse.VisitListTagsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDAG operation middleware
func (sh *strictHandler) DeleteDAG(w http.ResponseWriter, r *http.Request, name string) {
	var request DeleteDAGRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDAG(ctx, request.(DeleteDAGRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDAG")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDAGResponseObject); ok {
		if err := validResponse.VisitDeleteDAGResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDAGDetails operation middleware
func (sh *strictHandler) GetDAGDetails(w http.ResponseWriter, r *http.Request, name string, params GetDAGDetailsParams) {
	var request GetDAGDetailsRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDAGDetails(ctx, request.(GetDAGDetailsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDAGDetails")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDAGDetailsResponseObject); ok {
		if err := validResponse.VisitGetDAGDetailsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostDAGAction operation middleware
func (sh *strictHandler) PostDAGAction(w http.ResponseWriter, r *http.Request, name string) {
	var request PostDAGActionRequestObject

	request.Name = name

	var body PostDAGActionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostDAGAction(ctx, request.(PostDAGActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostDAGAction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostDAGActionResponseObject); ok {
		if err := validResponse.VisitPostDAGActionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDAGSpec operation middleware
func (sh *strictHandler) GetDAGSpec(w http.ResponseWriter, r *http.Request, name DAGName) {
	var request GetDAGSpecRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDAGSpec(ctx, request.(GetDAGSpecRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDAGSpec")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDAGSpecResponseObject); ok {
		if err := validResponse.VisitGetDAGSpecResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateDAGSpec operation middleware
func (sh *strictHandler) UpdateDAGSpec(w http.ResponseWriter, r *http.Request, name DAGName) {
	var request UpdateDAGSpecRequestObject

	request.Name = name

	var body UpdateDAGSpecJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateDAGSpec(ctx, request.(UpdateDAGSpecRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateDAGSpec")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateDAGSpecResponseObject); ok {
		if err := validResponse.VisitUpdateDAGSpecResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9w8a3PbtpZ/BcO9M/d2Vo7dpv1w/c3XThzvuI7HTrez23gzEHkk4YYEGACUrXb833fO",
	"AcCHCFKUnbZJP9ki8Tg47xf4W5KqolQSpDXJ8W9JyTUvwIKmX2cn51e8APw3A5NqUVqhZHKcSF4AUwtm",
	"V8DOTs6TWSLwccntKpnRWz8omSUaPlVCQ5YcW13BLDHpCgqOa/5NwyI5Tv7jsIHh0L01h2Hrx8dZcs2X",
	"ERhKvgQmq2IOGkERFgrDrGILsOmK/SODBa9yy4Rh334TAPxUgd40EOISSRsiPyk5/naWFEKKoirof7sp",
	"cbyQFpagHVCg43Btg1SCZgRrG6SXRzNW8AeC7uhoED6/RxTEH45mScEfPIxHR0c7QH4MqwTS9kE/VZro",
	"yVIlF2JZaY4v8JflQgq5ZPdKf1zk6p5lsBBS0GsuM1aA5Rm3PJklpVYlaCvA7ePAvUa+Mv0d/WtW8x1b",
	"87wCw4Rk/3X79ootlC64ZWLBpLLMlJCKhYCMcct0Ja0gFvNnNVYLuUweZ8lZe5PtPd9UBZcHGnjG5zmw",
	"1ssWS//dsLLSpTJA55vDiq+F0rHNzrWqyv42l2opUp6zJb5G3KkF05BzCxluYPBoTOkll+JXwjPPw5Ym",
	"tk1cEn+S4lMFTGQgLWJG07L+EOxe2JWQTFjjwIitO0SaS2EswtyQBrnSMLvilqVcsjmwkhsDGUpd2LFD",
	"FxIAXLm3qX/AteYb/H2briCrchgGw7gRiEh4KDUYI5Q0ng+RM1cgayjMSlV5hpC0oRjTNzUAEeDe8eUI",
	"fixfOlqm3MJSafErgoNMsxC5BTwx0XsPfDy2teYvjvJ39SA1/zekltj85PwkjTO5e46UQTKBRjmCjKka",
	"Ry/YtTJGoATUIpfmVQbH7+UBM5Zre8xu8U+YQc8rU4LMjtmt+6fzzqoSp6iy/VSD1ZtjdoN/6HnODfEI",
	"viy4/nhgqjQFY47Zj1x/7Axh3DD/dlHl9YQFFzlkA+PdS4KHr+GY3fI10KC00hqkxaPZtvFyQCJvI5Rk",
	"2eo3ySwBiQr1l4QwgprYHRz/s6ok+2ZJZ7fPEn46YHAsXztbKLu0bKmsk/MzsFzk7/i8T84LmQnkL8Pu",
	"VyJdoVDa1hmQzgiHANqmBbOtEBjUm8ksWQljFQGbq6W3Ksj0+gB/j0IV1d2WjhexGEI6vY0DvxSLkPNN",
	"f7d3ogBc2UCqZEb+wz0Xls1hgbaQiI4C3Dg623b1DzY2r+R6WBWBXAutZIFsvuZa4JZ0JgP1keAB0grP",
	"tJd+/oNs3Bsusxz0W7lLXTcDcZYw9gYsWkAlz/gmwlVXtVOW8Y3x4sKFZE4k6BC5WpoogS9VyuPUveZ2",
	"1bZ+C5FHue9SLc+EjjC70JCiSDJ0nQlbBI5cIjS0XBRPP/IHVPBruKlk5LQ/Orew5R2nSjb6D0qHAbKO",
	"/eP+pR2Na02STp6riXnA4Z3bvqgMSg76t0GAAgAIWTAKk1yM9tZfnQ90i1wzAllgKqdeSKe2gsNJu1so",
	"vzbv67WIkStoApIKkglniMfNogvIdsTEZAK0VhFdQo9ZAcZgsCkWjMtNTAzjME/VZLfOpdhJSxwVPAec",
	"5rwmxOj2zj+vwK6gUSXCBC+TPCcPwVypHLjsUee1g9Px2W3wd5rtBgj3xnlCZxiy9m12YxPQqcS4lliM",
	"e3buEu5ciyy+Dr5pZq+FqXju7eBUoTg7Ob9US1zowkIRF8w2qoedtD4LElTA09U+OuLs5LxH3FHxqdGz",
	"DeoAZdrHjWMU4STY0URuY7VLG0/m/kIOlOCCofZiSmegIWPzDdu2KmMIuVIZeL6LUCduS69a6TPcuy9o",
	"MR00q48zgLrdm52dnM9qm1aRRU9mieOI5DjRsIQHRCK3FjRO/r9f+MGvJwf/e3Twzw8Hd//5tyQeI+zJ",
	"hGrhZInEy4WdqKfTlcgzJlVGTk+Xkq+FFGYF2YntL3/z+vTly5f/JLIZy4uyawhxk4WfPuCcjevD4IpN",
	"z8pc9fKj/Yl0zBHGFDITa5FVPPfW1ftYe5pV3CfGmW/lKZcp5FPnv5WvHoSdPvo1F3mlYfqEWx86T5ww",
	"5E1e1xnsrYgx6pKKiEG61goBYRdn7Qh7yFu+gU8VGHuR7eMyI0tqN3HAyGr7ZF43bvZzrXcz/h082Glz",
	"aOS28mowNAuKrDHUzTRHjSAYbSTM2tLv5HVAA7rl0Cd4skF0iklIY1E8nuimtYzjV+CtxWz6F+WwDeDw",
	"HCRokTIgXGowpZIGmJ+3TbkUFccOTNBGp17DZEMsdJK5II7nfuswMgK6p3BE0a+Utn5+GLTLDaAjNGsO",
	"ourUHzXGcrgG2ZaU15ktXIXyR4TnJn8459mHRk1JZT8sVEW5T1SAWvL8Q5hSSV7ZFcZfxAQ4c8kt3PMN",
	"pT0LZeEDWvZ6As818GzzQVdSumwUrt/8Cu/hQRhrosnJTraoF8e30pHk6K5BWrZyU8g2xN35aVYxBKtT",
	"bGIYO9EihuET7aEb/hhhhTfAc7u68WIRMSVdgamN04rmsXQF6UcGMiuVkH1xMrVq6a76dg2a53lYxXQd",
	"bdBraHOYG7UhBgr/x0hdm7sIqUNei9ZmQwngqqQ3fTl009zrVio4auzXoE00ERiA8AN65x2X6zpPH9av",
	"wW2fPCbul8LYd3y5H5FzYUj0kUyWL/vONmmKkaQLybBhIFNVoSKAjGWVDtqk0RjT03LjSR4XqQRYn5jH",
	"eedm+7PFkHkVVZuNR87ltlMefHLechG3/AUl4RSxNJaTbmpcDCU8B5eBXJBVK8EpagoColw51cWoQ926",
	"LBVxN54UZrlVnxpj4ewDX8hJR6MtqiLuRCdV5BjGsEVpDSt4Bl65oavSibdbWHya000nf7bH3U0iTPe6",
	"m3nO83Z52skmoy0etw4vl1QYHPS94457iyyzFscPydjtgOm4qgry57zN2PZUQgED3QhXxT1+L4+O2fvk",
	"StlAg/fJe/ktPrtxngT+/g5/v3Z14eS9fIk/nZn3T77HJ97e4u8f6PdHUZbufWOwjmbfzr6bvZx9P/vh",
	"Llo76RJkVznQn7RdFQxWWDpfLxhK2RwRHaraTapFOaUD0b8tQTTuEFGbes2XQtaFrS1n2eE63uEUCNHq",
	"wIpKlISHgRXwzc7ppYb1QOuXhrVQldm5hFWW57hGhNvoXatEVtKwwVVuIFU6m7CO9gOjXWNtiessO+ug",
	"vAN5C5EtpMSE61oZW/eE7OcTlMr7BJLxunUk7iFfwf1A1gvuyQ5KXsAsGBy/mgZT5RYy53hLNzLqGPVP",
	"1a6bRbI1zdtuzc5wKwy1BvjKnZcaxkPCNx4ADO/1qi664WTnIFvFYM3zituoxXr1UEJqY2F0eONRE1zG",
	"5jB+WecPTsDTDbkK1yoX6WZKRERIcLay1XHQRcYFundrnu/TOWHvAeSWER5InSHA4wkGZ19dKXMOvsmF",
	"+pgWPpyKZhx6yBkuroY3Wy0sC8ceUaeu4YMInjWSrsMooc2Ghbz6rnigtf7dyFl01Ku6VMteUoswGWbF",
	"ON5CzKXCpVL/Mu7U7U5P1duOOHZbxw/rzmrIolgArtPV2cm5+ZHbdBUvGPmMlqs4GJrBChze8dx7GLkU",
	"EmJtFTZdUW+GkDCKGCHBuaOxmEbWbcv3K9AQ4OHo8LvsyoBzGofK9egRSFQHR7Ae7G7zQ6t1YG1vM47x",
	"G1JZcZRftEIkh3Cv4Oq6XRzn0wvgRAcwo9RuoRYMu8cfde5qUjdChLueVN8rAtMM2btInc8NDceMkuJ5",
	"LrQvE/x+HnTEY74b4OuxwuFpq2dzq264b4WQfdklQjYH19ZD7TPZPv1TN64NqumfMpF2qS+3Fhbw/+R6",
	"GPvLFsQGwvBhhfDcoLMh7p5x51bgeRdFNZSj1sJy87GbUCN33jevGzTgIUeEch/v+DjRY4lErpdVgWRC",
	"0UAhCSKSqqLgXeuwM2d5WmQ/C7uK73jq8nj1ysyt0+p26MDi5T7GoqcetN4W/+KmWb7VeocoVJVtNoj3",
	"Q5cgsx0dfe1GTIqq0nCquhfSZ9Ti3ZA7UfiM1ul7BKqOEDIVb5SNdt3+rPRHpEBWd99SgSg0Rter/t20",
	"+CLSgyvyt3Ig91qHMIoZkBmDgoucSYW6zzUTG4xh6mxsPJDZvxe3nZQeaT55W9myimiK//ZN48xdg1DU",
	"jQxthCg3cw/z1GrI2BI6U82n2qbP0rU7zKjPadvdDrvH1uqMxblVhO9vPVq2W7RbqpRGx0JZ/D9EJp2U",
	"v1cOpEXdqOGegQx0hKUxJGva1FNeWlfyMZbLjOusrh7HVlQxbtu54hCzTe3QRZMzOUZumRdfI/gDo+Qx",
	"/3FKSt91RQ2m9HeG04+zxEBaaWE3t7ikOzIvxTv1EYhH58A16NehVVCV3DUPEgSktWhAc4CVtVTHnnMj",
	"0pPKrqhqXI/Gp9uDEQwki2vXkJanhG5/G/Z/lOXsDS94xpNZUunczzPHh4dLYVfV/EWqisONspavisy1",
	"cHT6Nq4v6hBZqzwPneKFksLfujjjy8pXbV8ksyQXKfgUqgfi/Pry4OWLozEAMr6sDpRe0j+H81zNDwsu",
	"5OHlxemrq9tXLxxoVlhkigR3bFV+j5PvXhy9OMIRqgTJS5EcJy/pEfVlrogwuDT9s4SYTwy20hJFPffG",
	"nO7iUDe6KsM1nDr7TzjwobprmkdTWrtY6M2TV+Db6NtXxH+Jc2Uz5JBy1Y+z3eP8VWcc2tMSFrQ7wnzD",
	"/K3y2HVp/6q5K91TGzvWtnw5sLR7M7zyHUqey6oTXb47OgpM7HUGL8vcm/7Dfxvn7zTrdVVNNloNb4hp",
	"VyB08Oe3rmFP7eYm1RAxa/CH9wCUnXrUqEluRm7rvMxV+T30nUUjWq+vItq1+EBRp0n8tfs9iLqz0ywG",
	"QbypzWnoqii43gQieHmkrohw8jvEozI2lpcG7uy/L760rvD3xN0Nds6jJ+W/VLZ5BktL78hO/eZDm6Yy",
	"bt+7w6yu4LEnhd9+BpCH8zYS7vMNSwlZ2aQE38hRvkpGdIzSreh1+fFx5qzVobMwg0bLJVzBhMKLYXNu",
	"XKWHM9LGPoTuMWuTqu1bpx5SnZnbWi+m8T+Nfrrkc+v/3QVaB3nrOtu0lq1Xo2ra02QfLe1S/2aIgD7Z",
	"b5q8N+4TcLtn6r1VZtjV3RXAGmnw+mqFzGM2ru9r+bL7uYSh+Y9VKGU81cqYsEXf9/PNc8/i8TEEbfcx",
	"fuWmudVZOUSu31DPPDpK5WBj10jpufG50PmGbpJ6H7dLITfSF9XGFOC7lU/tPPvbTbsV4Pfxi7ENEfMN",
	"c0eneOh7N+H3pSB1pyjrS4FfHO84Otb10Z5nNyraWbvUTRf9mlwzfUhgRl84mLlwL9Qbuox0DrZ1e+VP",
	"Y6ZenHYbMjPj3z2JR27zZI+PjjXfYBkDg253hw9dNFW2ARA0fKJazz4HDtn3yK2/yA4+YfVn+idLsJQ8",
	"32bDJ9b5+ze5qFxQRyxR3dKJaPqtWH94RLt1y3zHkdujXd7wJx1pvPrp5pJ680iNkkj7Qka+ieeKfQZ0",
	"ypcfqKOomzjd1UjsZ7xz6ax+l5jNawVxPeWOk1so9ED89Zy5c7A++q7vjE0L4K97dVDy2yiD9w94sXwx",
	"c3WNGX2I65vwqa+lWIP0gthV9p1u0T/Zc3haimFbK9EqbK6yzb49rTydkndqsPXo0TV+O7DVkREKdB6Q",
	"3SUvvbOXwo9gF2dbq8eWM9Hqe2Nmut26luslWBOpifQWpq9zRa6BhTwzPFjN3Te8doK5pQr8sKdlfj5f",
	"bBLvqv56NZBXJC2xUHLI59wKVw7pQ3K7gkzKLJSQdnVFzNO8dd+l26+kUKcJP2/SfWLC2/ti/ot6032B",
	"gLm+WqWoyC2345qgGwR/WZvo2aFvEGPV45/KjBLaU7jNjf08DPc5suHDzBCS89MZ4hnqcSKzfP/lytUW",
	"QvYQjQu55rnI3IZfnEQ4hh0RClTM7sL0JHU8chub8gHCGpZRSxjIVEA0M+Duk/+eWcCtG+tPVGjbzhKE",
	"izbgSdJG9JuBy+4B3WZjLBSI8FaLBCmNpjnilzsM4Ft9DvQAtYXDcMyfpkaDk+uL5oq46yf4zeHi8fjw",
	"8LeVMvbxkJficP1dgp6W/6InHnJVxwj+3EmuUp7T422kvVHGdpx3v+dj9LvirhejdUXf/aRGB8LDXY2d",
	"vtPnWcb5uwWXfBmaLJr2Oiru/MN9+hIydpJu0lyk7FzzcmW+aSIJ4vRIaoQo0rSA+r2aHg4qhIetySI0",
	"TR2tlIkj7OPd4/8HAAD//6MlhXwEXwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
