// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	ApiTokenScopes  = "apiToken.Scopes"
	BasicAuthScopes = "basicAuth.Scopes"
)

// Defines values for DAGAction.
const (
	DAGActionMarkFailed  DAGAction = "mark-failed"
	DAGActionMarkSuccess DAGAction = "mark-success"
	DAGActionRename      DAGAction = "rename"
	DAGActionRetry       DAGAction = "retry"
	DAGActionSave        DAGAction = "save"
	DAGActionStart       DAGAction = "start"
	DAGActionStop        DAGAction = "stop"
	DAGActionSuspend     DAGAction = "suspend"
)

// Defines values for DAGDetailTab.
const (
	DAGDetailTabHistory      DAGDetailTab = "history"
	DAGDetailTabLog          DAGDetailTab = "log"
	DAGDetailTabSchedulerLog DAGDetailTab = "scheduler-log"
	DAGDetailTabSpec         DAGDetailTab = "spec"
	DAGDetailTabStatus       DAGDetailTab = "status"
)

// Defines values for ErrorCode.
const (
	ErrorCodeAlreadyRunning  ErrorCode = "already_running"
	ErrorCodeBadGateway      ErrorCode = "bad_gateway"
	ErrorCodeBadRequest      ErrorCode = "bad_request"
	ErrorCodeInternalError   ErrorCode = "internal_error"
	ErrorCodeNotFound        ErrorCode = "not_found"
	ErrorCodeNotRunning      ErrorCode = "not_running"
	ErrorCodeRemoteNodeError ErrorCode = "remote_node_error"
	ErrorCodeUnauthorized    ErrorCode = "unauthorized"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusHealthy   HealthResponseStatus = "healthy"
	HealthResponseStatusUnhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for NodeStatus.
const (
	NodeStatusN0 NodeStatus = 0
	NodeStatusN1 NodeStatus = 1
	NodeStatusN2 NodeStatus = 2
	NodeStatusN3 NodeStatus = 3
	NodeStatusN4 NodeStatus = 4
	NodeStatusN5 NodeStatus = 5
)

// Defines values for NodeStatusText.
const (
	NodeStatusTextCanceled   NodeStatusText = "canceled"
	NodeStatusTextFailed     NodeStatusText = "failed"
	NodeStatusTextFinished   NodeStatusText = "finished"
	NodeStatusTextNotStarted NodeStatusText = "not started"
	NodeStatusTextRunning    NodeStatusText = "running"
	NodeStatusTextSkipped    NodeStatusText = "skipped"
)

// Defines values for RunStatus.
const (
	RunStatusN0 RunStatus = 0
	RunStatusN1 RunStatus = 1
	RunStatusN2 RunStatus = 2
	RunStatusN3 RunStatus = 3
	RunStatusN4 RunStatus = 4
)

// Defines values for RunStatusText.
const (
	RunStatusTextCancelled  RunStatusText = "cancelled"
	RunStatusTextFailed     RunStatusText = "failed"
	RunStatusTextFinished   RunStatusText = "finished"
	RunStatusTextNotStarted RunStatusText = "not started"
	RunStatusTextRunning    RunStatusText = "running"
)

// DAG Core DAG configuration containing workflow definition and metadata
type DAG struct {
	// DefaultParams Default parameter values in JSON format if not specified at runtime
	DefaultParams *string `json:"DefaultParams,omitempty"`

	// Description Human-readable description of the DAG's purpose and behavior
	Description *string `json:"Description,omitempty"`

	// Group Logical grouping of related DAGs for organizational purposes
	Group *string `json:"Group,omitempty"`

	// Name Unique identifier for the DAG within its group
	Name string `json:"Name"`

	// Params List of parameter names that can be passed to the DAG at runtime
	Params *[]string `json:"Params,omitempty"`

	// Schedule List of scheduling expressions defining when the DAG should run
	Schedule *[]Schedule `json:"Schedule,omitempty"`

	// Tags List of tags for categorizing and filtering DAGs
	Tags *[]string `json:"Tags,omitempty"`
}

// DAGAction Action to be performed on the DAG. Possible values include:
// - start: Start the DAG
// - suspend: Suspend the DAG
// - stop: Stop the DAG
// - retry: Retry the last run
// - mark-success: Mark the last run as successful
// - mark-failed: Mark the last run as failed
// - save: Save the current state of the DAG
// - rename: Rename the DAG
type DAGAction string

// DAGDetailTab Indicates which part of the DAG to retrieve
type DAGDetailTab string

// DAGDetails Detailed DAG configuration information
type DAGDetails struct {
	// DefaultParams Default parameter values in JSON format if not specified at runtime
	DefaultParams *string `json:"DefaultParams,omitempty"`

	// Delay Time in seconds to wait before starting the DAG
	Delay *int `json:"Delay,omitempty"`

	// Description Human-readable description of the DAG's purpose and behavior
	Description *string `json:"Description,omitempty"`

	// Env List of environment variables to set before executing
	Env *[]string `json:"Env,omitempty"`

	// Group Logical grouping of related DAGs for organizational purposes
	Group *string `json:"Group,omitempty"`

	// HandlerOn Configuration for event handlers in a DAG
	HandlerOn *HandlerOn `json:"HandlerOn,omitempty"`

	// HistRetentionDays Number of days to retain historical logs
	HistRetentionDays *int `json:"HistRetentionDays,omitempty"`

	// Location Path to the DAG file
	Location *string `json:"Location,omitempty"`

	// LogDir Directory path for storing log files
	LogDir *string `json:"LogDir,omitempty"`

	// MaxActiveRuns Maximum number of concurrent steps to run
	MaxActiveRuns *int `json:"MaxActiveRuns,omitempty"`

	// Name Unique identifier for the DAG within its group
	Name string `json:"Name"`

	// Params List of parameter names that can be passed to the DAG at runtime
	Params *[]string `json:"Params,omitempty"`

	// Preconditions Conditions that must be met before the DAG can start
	Preconditions *[]Precondition `json:"Preconditions,omitempty"`

	// Schedule List of scheduling expressions defining when the DAG should run
	Schedule *[]Schedule `json:"Schedule,omitempty"`

	// Steps List of steps to execute in the DAG
	Steps *[]Step `json:"Steps,omitempty"`

	// Tags List of tags for categorizing and filtering DAGs
	Tags *[]string `json:"Tags,omitempty"`
}

// DAGFile DAG file with its status information
type DAGFile struct {
	// DAG Core DAG configuration containing workflow definition and metadata
	DAG DAG `json:"DAG"`

	// Error Error message if any
	Error *string `json:"Error,omitempty"`

	// File Path to the DAG file
	File string `json:"File"`

	// Status Current status of a DAG run
	Status DAGStatus `json:"Status"`

	// Suspended Whether the DAG is suspended
	Suspended bool `json:"Suspended"`
}

// DAGHistoryData Historical run data for a DAG
type DAGHistoryData struct {
	// GridData Grid data for visualization
	GridData []DAGLogGridItem `json:"GridData"`

	// StatusDetails Detailed status information for each run
	StatusDetails []DAGStatusDetails `json:"StatusDetails"`
}

// DAGLogGridItem Grid item for log visualization
type DAGLogGridItem struct {
	// History Status of the step ordered by time
	History []NodeStatus `json:"History"`

	// Name Name of the step
	Name string `json:"Name"`
}

// DAGName Name of the DAG, must be unique
type DAGName = string

// DAGStatus Current status of a DAG run
type DAGStatus struct {
	// FinishedAt RFC 3339 timestamp when the DAG run finished
	FinishedAt string `json:"FinishedAt"`

	// Log Path to the log file
	Log *string `json:"Log,omitempty"`

	// Name Name of the DAG being executed
	Name string `json:"Name"`

	// Params Runtime parameters passed to the DAG in JSON format
	Params *string `json:"Params,omitempty"`

	// Pid Process ID of the DAG run
	Pid *int `json:"Pid,omitempty"`

	// RequestId Unique identifier for the DAG run request
	RequestId string `json:"RequestId"`

	// StartedAt RFC 3339 timestamp when the DAG run started
	StartedAt string `json:"StartedAt"`

	// Status Numeric status code indicating current run state:
	// 0: "Not started"
	// 1: "Running"
	// 2: "Failed"
	// 3: "Cancelled"
	// 4: "Success"
	Status RunStatus `json:"Status"`

	// StatusText Human-readable status description for the DAG run
	StatusText RunStatusText `json:"StatusText"`
}

// DAGStatusDetails Detailed status of a DAG run including child nodes
type DAGStatusDetails struct {
	// FinishedAt RFC3339 timestamp when the DAG run finished
	FinishedAt string `json:"FinishedAt"`

	// Log Path to the log file
	Log string `json:"Log"`

	// Name Name of the DAG
	Name string `json:"Name"`

	// Nodes Status of individual steps within the DAG
	Nodes []Node `json:"Nodes"`

	// OnCancel Status of an individual step within a DAG run
	OnCancel *Node `json:"OnCancel,omitempty"`

	// OnExit Status of an individual step within a DAG run
	OnExit *Node `json:"OnExit,omitempty"`

	// OnFailure Status of an individual step within a DAG run
	OnFailure *Node `json:"OnFailure,omitempty"`

	// OnSuccess Status of an individual step within a DAG run
	OnSuccess *Node `json:"OnSuccess,omitempty"`

	// Params Parameters in JSON format
	Params *string `json:"Params,omitempty"`

	// Pid Process ID of the DAG run
	Pid int `json:"Pid"`

	// RequestId Unique identifier for the run request
	RequestId string `json:"RequestId"`

	// StartedAt RFC3339 timestamp when the DAG run started
	StartedAt string `json:"StartedAt"`

	// Status Numeric status code indicating current run state:
	// 0: "Not started"
	// 1: "Running"
	// 2: "Failed"
	// 3: "Cancelled"
	// 4: "Success"
	Status RunStatus `json:"Status"`

	// StatusText Human-readable status description for the DAG run
	StatusText RunStatusText `json:"StatusText"`
}

// DAGStatusFileDetails Detailed status information for a DAG instance
type DAGStatusFileDetails struct {
	// DAG Detailed DAG configuration information
	DAG DAGDetails `json:"DAG"`

	// Error Error message if any
	Error *string `json:"Error,omitempty"`

	// File Path to the DAG file
	File string `json:"File"`

	// Status Detailed status of a DAG run including child nodes
	Status DAGStatusDetails `json:"Status"`

	// Suspended Whether the DAG is suspended
	Suspended bool `json:"Suspended"`
}

// Error Generic error response object
type Error struct {
	// Code Error code indicating the type of error
	Code ErrorCode `json:"code"`

	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Short error message
	Message string `json:"message"`
}

// ErrorCode Error code indicating the type of error
type ErrorCode string

// HandlerOn Configuration for event handlers in a DAG
type HandlerOn struct {
	// Cancel Individual task within a DAG that performs a specific operation
	Cancel *Step `json:"Cancel,omitempty"`

	// Exit Individual task within a DAG that performs a specific operation
	Exit *Step `json:"Exit,omitempty"`

	// Failure Individual task within a DAG that performs a specific operation
	Failure *Step `json:"Failure,omitempty"`

	// Success Individual task within a DAG that performs a specific operation
	Success *Step `json:"Success,omitempty"`
}

// HealthResponse Response object for the health check endpoint
type HealthResponse struct {
	// Status Overall health status of the server
	Status HealthResponseStatus `json:"status"`

	// Timestamp Current server time
	Timestamp string `json:"timestamp"`

	// Uptime Server uptime in seconds
	Uptime int `json:"uptime"`

	// Version Current version of the server
	Version string `json:"version"`
}

// HealthResponseStatus Overall health status of the server
type HealthResponseStatus string

// ListTagResponse Response object for listing all tags
type ListTagResponse struct {
	// Errors List of errors encountered during the request
	Errors []string `json:"Errors"`

	// Tags List of unique tags
	Tags []string `json:"Tags"`
}

// Node Status of an individual step within a DAG run
type Node struct {
	// DoneCount Number of successful completions for repeating steps
	DoneCount int `json:"DoneCount"`

	// Error Error message if the step failed
	Error *string `json:"Error,omitempty"`

	// FinishedAt RFC3339 timestamp when the step finished
	FinishedAt string `json:"FinishedAt"`

	// Log Path to step-specific log file
	Log string `json:"Log"`

	// RetryCount Number of retry attempts made for this step
	RetryCount int `json:"RetryCount"`

	// StartedAt RFC3339 timestamp when the step started
	StartedAt string `json:"StartedAt"`

	// Status Numeric status code indicating current node state:
	// 0: "Not started"
	// 1: "Running"
	// 2: "Failed"
	// 3: "Cancelled"
	// 4: "Success"
	// 5: "Skipped"
	Status NodeStatus `json:"Status"`

	// StatusText Human-readable status description for the node
	StatusText NodeStatusText `json:"StatusText"`

	// Step Individual task within a DAG that performs a specific operation
	Step Step `json:"Step"`
}

// NodeStatus Numeric status code indicating current node state:
// 0: "Not started"
// 1: "Running"
// 2: "Failed"
// 3: "Cancelled"
// 4: "Success"
// 5: "Skipped"
type NodeStatus int

// NodeStatusText Human-readable status description for the node
type NodeStatusText string

// Pagination defines model for Pagination.
type Pagination struct {
	// CurrentPage current page number
	CurrentPage int `json:"currentPage"`

	// NextPage next page number
	NextPage int `json:"nextPage"`

	// PrevPage previous page number
	PrevPage int `json:"prevPage"`

	// TotalPages total number of pages
	TotalPages int `json:"totalPages"`

	// TotalRecords total number of records
	TotalRecords int `json:"totalRecords"`
}

// PostDAGActionResponse Response object for posting an action to a DAG
type PostDAGActionResponse struct {
	// NewName New DAG name, if the action resulted in a new DAG
	NewName *string `json:"NewName,omitempty"`
}

// Precondition Precondition that must be satisfied before running a step or DAG
type Precondition struct {
	// Condition Expression or check to evaluate
	Condition *string `json:"Condition,omitempty"`

	// Expected Expected result of the condition evaluation
	Expected *string `json:"Expected,omitempty"`
}

// RepeatPolicy Configuration for step retry behavior
type RepeatPolicy struct {
	// Interval Time in seconds to wait between retry attempts
	Interval *int `json:"Interval,omitempty"`

	// Repeat Whether the step should be retried on failure
	Repeat *bool `json:"Repeat,omitempty"`
}

// RunStatus Numeric status code indicating current run state:
// 0: "Not started"
// 1: "Running"
// 2: "Failed"
// 3: "Cancelled"
// 4: "Success"
type RunStatus int

// RunStatusText Human-readable status description for the DAG run
type RunStatusText string

// Schedule Schedule configuration for DAG run
type Schedule struct {
	// Expression Cron expression or schedule pattern
	Expression string `json:"Expression"`
}

// SchedulerLog Log information for the scheduler
type SchedulerLog struct {
	// Content Log content
	Content string `json:"Content"`

	// LogFile Path to the scheduler log file
	LogFile string `json:"LogFile"`
}

// SearchDAGsMatchItem Details of a search match within a DAG
type SearchDAGsMatchItem struct {
	// Line Matching line content
	Line string `json:"Line"`

	// LineNumber Line number where match was found
	LineNumber int `json:"LineNumber"`

	// StartLine Start line for context
	StartLine int `json:"StartLine"`
}

// SearchDAGsResultItem Individual search result item for a DAG
type SearchDAGsResultItem struct {
	// DAG Core DAG configuration containing workflow definition and metadata
	DAG DAG `json:"DAG"`

	// Matches Details of where matches were found
	Matches []SearchDAGsMatchItem `json:"Matches"`

	// Name Name of the matching DAG
	Name string `json:"Name"`
}

// Step Individual task within a DAG that performs a specific operation
type Step struct {
	// Args List of arguments to pass to the command
	Args *[]string `json:"Args,omitempty"`

	// CmdWithArgs Complete command string including arguments to execute
	CmdWithArgs *string `json:"CmdWithArgs,omitempty"`

	// Command Base command to execute without arguments
	Command *string `json:"Command,omitempty"`

	// Depends List of step names that must complete before this step can start
	Depends *[]string `json:"Depends,omitempty"`

	// Description Human-readable description of what the step does
	Description *string `json:"Description,omitempty"`

	// Dir Working directory for executing the step's command
	Dir *string `json:"Dir,omitempty"`

	// MailOnError Whether to send email notifications on step failure
	MailOnError *bool `json:"MailOnError,omitempty"`

	// Name Unique identifier for the step within the DAG
	Name string `json:"Name"`

	// Output Variable name to store the step's output
	Output *string `json:"Output,omitempty"`

	// Params Parameters to pass to the sub DAG in JSON format
	Params *string `json:"Params,omitempty"`

	// Preconditions Conditions that must be met before the step can start
	Preconditions *[]Precondition `json:"Preconditions,omitempty"`

	// RepeatPolicy Configuration for step retry behavior
	RepeatPolicy *RepeatPolicy `json:"RepeatPolicy,omitempty"`

	// Run Sub DAG to run
	Run *string `json:"Run,omitempty"`

	// Script Script content if the step executes a script file
	Script *string `json:"Script,omitempty"`

	// Stderr File path for capturing standard error
	Stderr *string `json:"Stderr,omitempty"`

	// Stdout File path for capturing standard output
	Stdout *string `json:"Stdout,omitempty"`
}

// StepLog Log information for a specific step
type StepLog struct {
	// Content Log content
	Content string `json:"Content"`

	// LogFile Path to the log file
	LogFile string `json:"LogFile"`

	// Step Status of an individual step within a DAG run
	Step Node `json:"Step"`
}

// Page defines model for page.
type Page = int

// PerPage defines model for perPage.
type PerPage = int

// ListDAGsParams defines parameters for ListDAGs.
type ListDAGsParams struct {
	// Page page number of items to fetch (default is 1)
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PerPage number of items per page (default is 30, max is 100)
	PerPage *PerPage `form:"perPage,omitempty" json:"perPage,omitempty"`

	// Name Filter DAGs by name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Tag Filter DAGs by tag
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// CreateDAGJSONBody defines parameters for CreateDAG.
type CreateDAGJSONBody struct {
	// Name Name of the DAG, must be unique
	Name DAGName `json:"name"`
}

// GetDAGDetailsParams defines parameters for GetDAGDetails.
type GetDAGDetailsParams struct {
	// Tab Specific part of the DAG to retrieve
	Tab *DAGDetailTab `form:"tab,omitempty" json:"tab,omitempty"`

	// ReqId Specific file related to the DAG
	ReqId *string `form:"reqId,omitempty" json:"reqId,omitempty"`

	// Step Step name within the DAG
	Step *string `form:"step,omitempty" json:"step,omitempty"`
}

// PostDAGActionJSONBody defines parameters for PostDAGAction.
type PostDAGActionJSONBody struct {
	// Action Action to be performed on the DAG. Possible values include:
	// - start: Start the DAG
	// - suspend: Suspend the DAG
	// - stop: Stop the DAG
	// - retry: Retry the last run
	// - mark-success: Mark the last run as successful
	// - mark-failed: Mark the last run as failed
	// - save: Save the current state of the DAG
	// - rename: Rename the DAG
	Action DAGAction `json:"action"`

	// Params Additional parameters for the action in JSON format
	Params *string `json:"params,omitempty"`

	// RequestId Unique request ID for the action
	RequestId *string `json:"requestId,omitempty"`

	// Step Step name if the action targets a specific step
	Step *string `json:"step,omitempty"`

	// Value Optional extra value for the action
	Value *string `json:"value,omitempty"`
}

// SearchDAGsParams defines parameters for SearchDAGs.
type SearchDAGsParams struct {
	// Q A search query string
	Q string `form:"q" json:"q"`
}

// CreateDAGJSONRequestBody defines body for CreateDAG for application/json ContentType.
type CreateDAGJSONRequestBody CreateDAGJSONBody

// PostDAGActionJSONRequestBody defines body for PostDAGAction for application/json ContentType.
type PostDAGActionJSONRequestBody PostDAGActionJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List DAGs
	// (GET /dags)
	ListDAGs(w http.ResponseWriter, r *http.Request, params ListDAGsParams)
	// Create a new DAG
	// (POST /dags)
	CreateDAG(w http.ResponseWriter, r *http.Request)
	// Delete a DAG
	// (DELETE /dags/{name})
	DeleteDAG(w http.ResponseWriter, r *http.Request, name string)
	// Get DAG details
	// (GET /dags/{name})
	GetDAGDetails(w http.ResponseWriter, r *http.Request, name string, params GetDAGDetailsParams)
	// Perform an action on a DAG
	// (POST /dags/{name})
	PostDAGAction(w http.ResponseWriter, r *http.Request, name string)
	// Health check endpoint
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Search DAGs
	// (GET /search)
	SearchDAGs(w http.ResponseWriter, r *http.Request, params SearchDAGsParams)
	// List all tags
	// (GET /tags)
	ListTags(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List DAGs
// (GET /dags)
func (_ Unimplemented) ListDAGs(w http.ResponseWriter, r *http.Request, params ListDAGsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new DAG
// (POST /dags)
func (_ Unimplemented) CreateDAG(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a DAG
// (DELETE /dags/{name})
func (_ Unimplemented) DeleteDAG(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get DAG details
// (GET /dags/{name})
func (_ Unimplemented) GetDAGDetails(w http.ResponseWriter, r *http.Request, name string, params GetDAGDetailsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Perform an action on a DAG
// (POST /dags/{name})
func (_ Unimplemented) PostDAGAction(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check endpoint
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search DAGs
// (GET /search)
func (_ Unimplemented) SearchDAGs(w http.ResponseWriter, r *http.Request, params SearchDAGsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all tags
// (GET /tags)
func (_ Unimplemented) ListTags(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDAGs operation middleware
func (siw *ServerInterfaceWrapper) ListDAGs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDAGsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameter("form", true, false, "perPage", r.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", r.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDAGs(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDAG operation middleware
func (siw *ServerInterfaceWrapper) CreateDAG(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDAG(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDAG operation middleware
func (siw *ServerInterfaceWrapper) DeleteDAG(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDAG(w, r, name)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDAGDetails operation middleware
func (siw *ServerInterfaceWrapper) GetDAGDetails(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDAGDetailsParams

	// ------------- Optional query parameter "tab" -------------

	err = runtime.BindQueryParameter("form", true, false, "tab", r.URL.Query(), &params.Tab)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tab", Err: err})
		return
	}

	// ------------- Optional query parameter "reqId" -------------

	err = runtime.BindQueryParameter("form", true, false, "reqId", r.URL.Query(), &params.ReqId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reqId", Err: err})
		return
	}

	// ------------- Optional query parameter "step" -------------

	err = runtime.BindQueryParameter("form", true, false, "step", r.URL.Query(), &params.Step)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "step", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDAGDetails(w, r, name, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDAGAction operation middleware
func (siw *ServerInterfaceWrapper) PostDAGAction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDAGAction(w, r, name)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchDAGs operation middleware
func (siw *ServerInterfaceWrapper) SearchDAGs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchDAGsParams

	// ------------- Required query parameter "q" -------------

	if paramValue := r.URL.Query().Get("q"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchDAGs(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTags operation middleware
func (siw *ServerInterfaceWrapper) ListTags(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenScopes, []string{})

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTags(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dags", wrapper.ListDAGs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dags", wrapper.CreateDAG)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/dags/{name}", wrapper.DeleteDAG)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dags/{name}", wrapper.GetDAGDetails)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dags/{name}", wrapper.PostDAGAction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search", wrapper.SearchDAGs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tags", wrapper.ListTags)
	})

	return r
}

type ListDAGsRequestObject struct {
	Params ListDAGsParams
}

type ListDAGsResponseObject interface {
	VisitListDAGsResponse(w http.ResponseWriter) error
}

type ListDAGs200JSONResponse struct {
	// Dags List of DAGs with their status and metadata
	Dags []DAGFile `json:"dags"`

	// Errors List of errors encountered during the request
	Errors     []string   `json:"errors"`
	Pagination Pagination `json:"pagination"`
}

func (response ListDAGs200JSONResponse) VisitListDAGsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListDAGs400JSONResponse Error

func (response ListDAGs400JSONResponse) VisitListDAGsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListDAGsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListDAGsdefaultJSONResponse) VisitListDAGsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateDAGRequestObject struct {
	Body *CreateDAGJSONRequestBody
}

type CreateDAGResponseObject interface {
	VisitCreateDAGResponse(w http.ResponseWriter) error
}

type CreateDAG201JSONResponse struct {
	// Name Name of the newly created DAG
	Name string `json:"name"`
}

func (response CreateDAG201JSONResponse) VisitCreateDAGResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDAG400JSONResponse Error

func (response CreateDAG400JSONResponse) VisitCreateDAGResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDAGdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateDAGdefaultJSONResponse) VisitCreateDAGResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteDAGRequestObject struct {
	Name string `json:"name"`
}

type DeleteDAGResponseObject interface {
	VisitDeleteDAGResponse(w http.ResponseWriter) error
}

type DeleteDAG204Response struct {
}

func (response DeleteDAG204Response) VisitDeleteDAGResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDAG404JSONResponse Error

func (response DeleteDAG404JSONResponse) VisitDeleteDAGResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDAGdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteDAGdefaultJSONResponse) VisitDeleteDAGResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetDAGDetailsRequestObject struct {
	Name   string `json:"name"`
	Params GetDAGDetailsParams
}

type GetDAGDetailsResponseObject interface {
	VisitGetDAGDetailsResponse(w http.ResponseWriter) error
}

type GetDAGDetails200JSONResponse struct {
	// DAG Detailed status information for a DAG instance
	DAG DAGStatusFileDetails `json:"DAG"`

	// Definition DAG definition
	Definition *string `json:"Definition,omitempty"`

	// Errors List of errors encountered during the request
	Errors []string `json:"Errors"`

	// HistoryData Historical run data for a DAG
	HistoryData *DAGHistoryData `json:"HistoryData,omitempty"`

	// LogUrl URL to access logs directly
	LogUrl *string `json:"LogUrl,omitempty"`

	// ScLog Log information for the scheduler
	ScLog *SchedulerLog `json:"ScLog,omitempty"`

	// StepLog Log information for a specific step
	StepLog *StepLog `json:"StepLog,omitempty"`

	// Title Title of the Page
	Title string `json:"Title"`
}

func (response GetDAGDetails200JSONResponse) VisitGetDAGDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDAGDetails404JSONResponse Error

func (response GetDAGDetails404JSONResponse) VisitGetDAGDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDAGDetailsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetDAGDetailsdefaultJSONResponse) VisitGetDAGDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostDAGActionRequestObject struct {
	Name string `json:"name"`
	Body *PostDAGActionJSONRequestBody
}

type PostDAGActionResponseObject interface {
	VisitPostDAGActionResponse(w http.ResponseWriter) error
}

type PostDAGAction200JSONResponse PostDAGActionResponse

func (response PostDAGAction200JSONResponse) VisitPostDAGActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostDAGActiondefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PostDAGActiondefaultJSONResponse) VisitPostDAGActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthdefaultResponse struct {
	StatusCode int
}

func (response GetHealthdefaultResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type SearchDAGsRequestObject struct {
	Params SearchDAGsParams
}

type SearchDAGsResponseObject interface {
	VisitSearchDAGsResponse(w http.ResponseWriter) error
}

type SearchDAGs200JSONResponse struct {
	// Errors Errors encountered during the search
	Errors []string `json:"Errors"`

	// Results Search results matching the query
	Results []SearchDAGsResultItem `json:"Results"`
}

func (response SearchDAGs200JSONResponse) VisitSearchDAGsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchDAGsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SearchDAGsdefaultJSONResponse) VisitSearchDAGsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListTagsRequestObject struct {
}

type ListTagsResponseObject interface {
	VisitListTagsResponse(w http.ResponseWriter) error
}

type ListTags200JSONResponse ListTagResponse

func (response ListTags200JSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTagsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListTagsdefaultJSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List DAGs
	// (GET /dags)
	ListDAGs(ctx context.Context, request ListDAGsRequestObject) (ListDAGsResponseObject, error)
	// Create a new DAG
	// (POST /dags)
	CreateDAG(ctx context.Context, request CreateDAGRequestObject) (CreateDAGResponseObject, error)
	// Delete a DAG
	// (DELETE /dags/{name})
	DeleteDAG(ctx context.Context, request DeleteDAGRequestObject) (DeleteDAGResponseObject, error)
	// Get DAG details
	// (GET /dags/{name})
	GetDAGDetails(ctx context.Context, request GetDAGDetailsRequestObject) (GetDAGDetailsResponseObject, error)
	// Perform an action on a DAG
	// (POST /dags/{name})
	PostDAGAction(ctx context.Context, request PostDAGActionRequestObject) (PostDAGActionResponseObject, error)
	// Health check endpoint
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Search DAGs
	// (GET /search)
	SearchDAGs(ctx context.Context, request SearchDAGsRequestObject) (SearchDAGsResponseObject, error)
	// List all tags
	// (GET /tags)
	ListTags(ctx context.Context, request ListTagsRequestObject) (ListTagsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListDAGs operation middleware
func (sh *strictHandler) ListDAGs(w http.ResponseWriter, r *http.Request, params ListDAGsParams) {
	var request ListDAGsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDAGs(ctx, request.(ListDAGsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDAGs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDAGsResponseObject); ok {
		if err := validResponse.VisitListDAGsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDAG operation middleware
func (sh *strictHandler) CreateDAG(w http.ResponseWriter, r *http.Request) {
	var request CreateDAGRequestObject

	var body CreateDAGJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDAG(ctx, request.(CreateDAGRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDAG")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDAGResponseObject); ok {
		if err := validResponse.VisitCreateDAGResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDAG operation middleware
func (sh *strictHandler) DeleteDAG(w http.ResponseWriter, r *http.Request, name string) {
	var request DeleteDAGRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDAG(ctx, request.(DeleteDAGRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDAG")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDAGResponseObject); ok {
		if err := validResponse.VisitDeleteDAGResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDAGDetails operation middleware
func (sh *strictHandler) GetDAGDetails(w http.ResponseWriter, r *http.Request, name string, params GetDAGDetailsParams) {
	var request GetDAGDetailsRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDAGDetails(ctx, request.(GetDAGDetailsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDAGDetails")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDAGDetailsResponseObject); ok {
		if err := validResponse.VisitGetDAGDetailsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostDAGAction operation middleware
func (sh *strictHandler) PostDAGAction(w http.ResponseWriter, r *http.Request, name string) {
	var request PostDAGActionRequestObject

	request.Name = name

	var body PostDAGActionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostDAGAction(ctx, request.(PostDAGActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostDAGAction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostDAGActionResponseObject); ok {
		if err := validResponse.VisitPostDAGActionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchDAGs operation middleware
func (sh *strictHandler) SearchDAGs(w http.ResponseWriter, r *http.Request, params SearchDAGsParams) {
	var request SearchDAGsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchDAGs(ctx, request.(SearchDAGsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchDAGs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchDAGsResponseObject); ok {
		if err := validResponse.VisitSearchDAGsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTags operation middleware
func (sh *strictHandler) ListTags(w http.ResponseWriter, r *http.Request) {
	var request ListTagsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTags(ctx, request.(ListTagsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTags")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTagsResponseObject); ok {
		if err := validResponse.VisitListTagsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc63PcOI7/V1i6rdqZunbsPObD+pvXThxfeRKXnbmpuySXYkvoFjcSqZBU2z0p/+9X",
	"AEk9qX44j81s7SdbEh8gQAA/AmB/TlJVVkqCtCY5/pxUXPMSLGj/tAT8m4FJtaisUDI5prdM1uUcNFML",
	"JiyUhlnFFmDTnP2UwYLXhWXCsMc/J7NEYJ9PNeh1MkskL8EPkcwSk+ZQcjcDdUqOH8+SUkhR1iX9b9cV",
	"thfSwhJ0cn8/SyrQV1G6hiRVoBnR2iXp6dGMlfyOqDs6mqTPzxEl8ZejWVLyO0/j0dHRFpLvwyjE07OT",
	"8zHpp0oDOzs5Z6mSC7GsNccP+GS5kEIu2a3SHxeFumUZLIQU9JnLjJVgecYtT2ZJpVUF2gpw8zhyr1Cg",
	"Zjyj/8wagbMVL2owTEj2XzevX7GF0iW3TCyYVJaZClKxEJAxbpmupRUlcsev1Vgt5DK5nyVn3UmGc76s",
	"Sy4PNPCMzwtgnY8oNJsTC/5qWFXrShmg9c0h5yuhdGyyc63qajzNpVqKlBdsiZ+Rd2rBNBTcQoYTGFwa",
	"U3rJpfiD+MyLMKWJTfOK9sRwlt+k+FQDExlIi5zRNKxfBLsVNheSCWscGbFxp0RzKYxFmlvR4K40zObc",
	"spRLNgdWcWMgQ60LM/bkQgqAI48m9S+41nyNzzdpDlldwDQZxrVARsJdpcEYoaTx+xB3Zg6yocLkqi4y",
	"pKRLxV80LJLj5D8OW2Nz6FXisCEgQtwbvtzAH8uXTpYpt7BUWvyB5OCmWYjCAq6Y5L0HP+5niYZPtdCQ",
	"JcdvneTfN43U/B+QWtrmJ+cnaXyTu/coGRQTaNQjyJhqePSIXSljBGpAo3JpUWdw/E4eMGO5tsfsBv+E",
	"HvS+NhXI7JjduH9636yqsIuqum81WL0+Ztf4h94X3NAewY8l1x8PTJ2mYMwx+5Xrj70mjBvmvy7qoumw",
	"4KKAbKK9+0j08BUcsxu+AmqU1lqDtLg0Cx1Nd0Ti3kYq8W/7JZklINGgvk2II2iJ3cLxP6tQoWiBCdri",
	"di3h0RGDbfkKqK3sy7Jjsk7Oz8ByUbzh87E4L2QmcH8ZdpuLNEeltJ01oJyRDgE0TYdmWyMxaDeTWZIL",
	"YxURW6il9yq46fUBPm+kKmq7LS0v4jGEdHYbG/4oHqHg6/Fsb0QJOLKBVMmM8MMtF5bNYYG+kISOCuz5",
	"nIz96nd2Ns/latoUgVwJrWSJ23zFtcApaU0GmiXBHaQ1rmkv+/ydfNxLLrMC9Gu5zVy3DbGXMPYaLHpA",
	"Jc/4OrKrXjWgLONr49WFC8mcStAiCrU0UQFfqpTHpXvFbd71fgtRRHffpVqeCR3Z7EJDiirJKhwJuUXk",
	"yCVSQ8NF+fQrv0MDv4LrWkZW+6uDhR10nCrZ2j+oHAfIO46X+y8NNK40aTohVxNDwOGbm76sDWoO4tug",
	"QIEApCw4hZ0gRnfqPx0GusFds4GysKmceSGb2trM3Wa3UP3Z0NcLERNXsASkFaQTzhFvdovuQLaJQ9gE",
	"XYDWKmJL6DUrwRg8bIoF43IdU8M4zbtashsHKbZT6htiF4eYkJvDWX/PwebQmhFhAsIk1ORnnytVAJcj",
	"ybxwNLo9dhOwTjvdhNBeOhR0hsfVsb9u/QECSjzT0vbifiv3hXauRRYfB7+0vVfC1LzwPnBXhTg7Ob9U",
	"SxzowkIZV0pc83aANt5+RBXwNN/HPjRSDTNuU52GPUNSJyTTXW6co0gn0Y7uccjVvmy8mMcDOVIC/ELL",
	"xZTOQEPG5ms29CibGPJKZdDu86F04n4U33bnHitZzP7MmuVMsG77ZGcn57PGn9XkzZNZ4nZEcpxoWMId",
	"MpFbCxo7/99bfvDHycH/Hh387cPB+//8SxI/H7QWYeBKO+ctx27SIb/h+rJ6IaQwOWQndjzO9YtT9vTp",
	"07+RZIzlZdX3c6imC99/AnttNncBae0edBmwlc3BuWRyfdk+2OfaQZgW+5gI1OmffKLDi4hxvdIKz6Ls",
	"4qxL6xTqu4ZPNRh7ke0L/ZD/2nWecBjaPlyyxnV/uCu6rmXHFdF/b+DO7tyNGg91smXWLOhn63/abt3V",
	"z7qbfEKJ97TnXZXy0Rvch2kuioxJldHZYS9F+7H1LNqRlrnBxguZiZXIal54kOqPKnuiU5wnZuRfy1Mu",
	"Uyh27f9aPr8TdvfWL7goag27d7jxEagdO0wZpqvWIP245ueLTM+/uOVBmQT1mLRDTms3WiME2Q9GmNz7",
	"L2NRSR545umgzT/T0adD9g91Aprg4TlI0CJlQLzUYColDTDfbyi5FM3HFk7QRKfezmRTW+gkcxERXvip",
	"Q8sI6V7CEXOfK219/9BoG66mJbRjTrLq1C81tuVwDPIwKW/CxDgKBWOJz20wfs6zD62xksp+WKiaEglo",
	"BrXkxYfQpZa8trnS4g/aBNhzyS3c8jXlEEpl4QP696YDLzTwbP1B11K60C6OH57eb4u0jmJgnVA+HRRX",
	"CORz14UcQvw4vJsrDIGeXRxhaLujGwzNd3SCrvl9RPIvgRc2v/ZaEPEfff1oPFJO/ViaQ/qRgcwqJeRY",
	"e8zEken1CjQvijCK6R9UQa+gu6FcqzXtl/B/TNSNj9twRqOx2VTypK7oy1jtXDf3uZNGiXr4FWgTDaIH",
	"InyD0Xo3q3GT4wrjN+R2Vx7T7kth7Bu+3E/IhTCk6Sgmy5djhE2GYUPAklTWMJCpqlHvIWNZrYPxaA3E",
	"7iHtzQFSd9IPtD4wBvrG9fZrizHzVdRKtjCcyyESD0B8OipwpiScIpc25XPa/DBDDS/ARe8X5MQqcHaZ",
	"kH90V+6KKJpQUZPSjaCLB52t3KgPPVhh7wOfBE03HrEoA7+VnZTNZtxaKCtrWMkz8MYNkUkvXtXh4sOQ",
	"Nq38i2F2Pwi3O85u+zmg7XIcO7uMrnrcOL5cUlJ9EmrHcXpHLLPOjp/Ssalo26u6JPjmfcYQmITkH6IG",
	"VwFx/E4eHbN3yStlgwzeJe/kY3x37YADPj/B5xeupiJ5J5/io3Pz/s0zfOP9LT7/Qs8fRVW5763DOpo9",
	"nj2ZPZ09m/3yPpp37AtkWyrdr7SbUQ9eWDpoFxylbJeI+KnBSI0qp7Qg+rejiMYtIupTr/hSyCYpPMDG",
	"jtfx6sAgiE71YlSjJNxNjIBftnavNKzi3fGLULXZOoRVlhc4RmS30bdOermiZpOjXEOqdLbDONo3jFZc",
	"djWuN+ysx/Ie5R1GdpgSU64rZWxTT7UfJqiUxwSS8absKo6QX8HtRKgLbskPSl7CLDgcP5oGUxcWMge8",
	"pWsZBUbjVXVzzpEQTfu1n+823ApDZTU+6+21hvGQMIkfAKbnet4krLGzA8hWMVjxouY26rGe31WQ2tip",
	"OXzxrAmQsV2MH9bhwR34dE1Q4UoVIl3vciIiJjhf2anW6TPjAuHdihf7VB3ZWwA5cMIT8TIkeHM8wflX",
	"VwYwB18gRjWAC3+cigYYxsxpAlkPdTs+nvbtvE7Ey0R9TD+49gUupsWse3qZgZuJOZfpQpDwZVBut3Dq",
	"GAXRrd5F9rVGVekpZigJZCEPuO381Rk/ZlYDxTqKYi/VchQzpJ0besUsjIUYhMWhUv8xDqK3R/+aaTcA",
	"6cHyw7izhrIoF4DrND87OTe/cpvm8QS3Dxi6tI6hHqzE5r2T0ogjl0JCrATMpjnVkQkJGxkjJDj4HztD",
	"yuaKxW0OGgI9HA9YLng1cRiIU+XqiYkkqtlBsu7sdndPo/Vo7U6zmePX5CLiLL/oHEkdw71DaeoM4jzf",
	"vViH5ABmo7Q7rAXDbvGhCQ3uVDkV2V0Pqkcow6aZwheRugTXNCwzKgp/rJpkveXmYz8aQFjEV60b1IZw",
	"wEUhxMs9TvSmKAjXy7pEpqGqV9yYoPKpKkveZ/XWgMtpmf0ubB6f8dQFIZqRmRunk5/t0eKLBmKaeepJ",
	"G03xd27a4Ts1d8hCVdt2gnghdAUy21LK163AJEiYhlU1RZA+HBAvg9zKwi+omb5Fohp4k6l4hWy03PZ3",
	"pT+iBLKm7Jai26Eiuhn1r6azLyLFt6J4LScCRw3+UsyAzBiUXBRMKovbl7vYlJJtKCmOwvYvwu1G1Dak",
	"y1/Xtqoj3vO/fbU4c/cfFJUhQ5chyvXco7alk0IeKJ2p57sWtnyVct3pjfol9brDM8PGpG63rcOhEe/o",
	"2TKsze4iQ2wdw4X4f3DzvXilNw5kRV2r6fxmBjqypRHftPXpKa+si1cby2XGddZkumIjqthu2zri1Gbb",
	"tTQXXc7OgLPjXnyA8ztCzk0R213ika6OYzIeuRWb3s8SA2mthV0jVC/dknkl3qiPQHt0DlyDfhHqBFXF",
	"XeUgUUBWixq0C8itpSTcnBuRntQ2p5RX0xrfDhsjGSgWl1qWlqfEbn8N9n+U5ewlL3nGk1lS68L3M8eH",
	"h0th83r+KFXl4VpZy/Myc+nmXo756qLBm1oVRSgRL5UU/rrFGV/WPuX0KJklhUjBx388EedXlwdPHx1t",
	"IiDjy/pA6SX9czgv1Pyw5EIeXl6cPn918/yRI80Ki5siwRk7aavj5Mmjo0dH2EJVIHklkuPkKb2iosyc",
	"BIND0z9LiMXawdZaoqoX3pnTJRwqQ1dVuH/ThC6JBx73ump5dKUNxLrIPCrw9fPdS9lv47uybXJId6vv",
	"Z9vb+TvO2HRkJSxot4T5mjzTxD1p/6m9JD0yG1vGtnw5MbT7Mj3ye9Q8FxIkuTw5Ogqb2NsMXlWFd/2H",
	"/zAO77Tj9U1NtjGV1wrT5iB0CE8M7l/vWspNpiHi1uC7JzCrXjB9o0tuWw5tXuZSlJ763qARqzc2Ed1E",
	"YpAoEvdsT4FurYiJzX4hV7wQWa8MWKuVyMBbM3/n/1vTES8Ccl6iLkuu12EjeJtAaeXA/fcoS2VsLNAE",
	"3GEQH73u/H7AyOS4xg7A+u30d5Wtv0CtpAfTWzSC4MRwX8k4xug3s7qG+5ElePwVSJ4+rEu4LdYsJWZl",
	"O53YNyzlR1QGL3s2R+H/cFrgdmk/H9NXhvuZc9eHn5Hx906aeIiOBYPwvfHRj/maLo15r9ZXDtfSx6T6",
	"DnmQY8j9Ya5XPy3cL6fYfOQ8+5t5P5f3LH4Hrt1ExZq5pWduFz379kKkZJqyPpL2w20fJ8cmvDiyoxvx",
	"XdaNFNO9nja6RHeGZ3SZeeYAXig76G+kc7Cd2tp/2mYaIbObcBbb/BMHcaw272G1neqK3/D5RjLoIme4",
	"095WCU+QoOETlWbvs+AQb4vcTIjM4I+o3w6Rbs93L8FSuGy4DR8YJh/XmVOAsMEHUdvSww/jzPF3x7CD",
	"S6Vbltxt7SIFv+lInvi360sqJSAzSirtQ5fFOh4d8jGPXS55U0KuHyrZVvfke7xxB9hxUtsWjYG42qUC",
	"2w0UUgiTxYV74ZN/e5ZzsB5hN3X0u4H0q1G+BbJQgvITPFo+mrn46Yx+6efn8FtCS7EC6dW/72J6JTX/",
	"ZLzysGPE0Ba2gHTfwh+e7nK+bbl179m1+cZE57wYEgGekO2hdb31xlUA4Bdng9Fjw5lolq91bv2SJsv1",
	"EqyJxF5HA9PP/0Rq5UM8C+6s5u5HgraSOTBAvtnDTndf7yQULz3bx+79WBbIG5KOWig5hXTxkOQuL2yN",
	"anbuV8RuRhDYxXNTRhlOkKmAKOx1dzuSbyjQwe2RB0pyqJMQit7AS6fL85cTF08Cu83aWCg9w13Md5Lh",
	"rp4ATKgrMmzOjSsc44zgqE9qj7jbViJsM/cnIfA8GC8GeT994fH0a+NfR3nnl2V2uwHyfCPo9DLZB3O6",
	"yhYzJUBfy2Lasg6cJ/B2z8qSThXNtssigayvA+l+LNPmORuPfqJq2f3yM+EaEasNgS2tjAmjjxMx/hrO",
	"N7NbwxtRf1450UGvc0drKKlO2pOMU5vwfPsej+id3CW9QKvi3EzMmFHy8OTqor2z5nKEn91i7o8PDz/n",
	"ytj7Q16Jw9WTBFGN/3k+5EPe4HHPw6RQKS/o9XD5L5WxPaDs57yP/kiwy6927gy6R0peEh/eN7wZAyy/",
	"/ZwfKLnky5A4bUtmyD385H7HDjJ2kq7TQqTsXPMqNz+3NpwYHwl+kFtqy7r8XG1elpJbYWo6F7SJ2k5Q",
	"xHm3+/f3/x8AAP//9jvG9EpaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
