name: ReleaseHelmCharts

on:
  push:
    branches:
      - main
    paths:
      - "charts/dagu/Chart.yaml"
      - "charts/dagu/values.yaml"
      - "charts/dagu/values.schema.json"
      - "charts/dagu/.helmignore"
      - "charts/dagu/README.md"
      - "charts/dagu/LICENSE*"
      - "charts/dagu/templates/**"
      - "charts/dagu/charts/**"
      - "charts/dagu/crds/**"
      - ".github/workflows/chart-release.yaml"

concurrency:
  group: chart-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
          pages_branch: gh-pages
          skip_existing: true
          mark_as_latest: false
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
