name: DockerImage Manual

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to build (e.g. v1.16.9 or main)"
        required: true
        type: string

jobs:
  docker-default:
    name: Build and push default image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DAGU_GITHUB_TOKEN }}

      - name: Resolve version
        id: get_version
        shell: bash
        run: |
          REF="${{ inputs.ref }}"
          case "$REF" in
            refs/tags/v*) VERSION="${REF#refs/tags/v}" ;;
            v*)           VERSION="${REF#v}" ;;
            refs/tags/*)  VERSION="${REF#refs/tags/}" ;;
            *)            VERSION="${REF}" ;;
          esac
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          build-args: |
            LDFLAGS=-X 'main.version=${{ env.VERSION }}-${{ env.SHORT_SHA }}'
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}

  docker-dev:
    name: Build and push dev image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DAGU_GITHUB_TOKEN }}

      - name: Resolve version
        id: get_version
        shell: bash
        run: |
          REF="${{ inputs.ref }}"
          case "$REF" in
            refs/tags/v*) VERSION="${REF#refs/tags/v}" ;;
            v*)           VERSION="${REF#v}" ;;
            refs/tags/*)  VERSION="${REF#refs/tags/}" ;;
            *)            VERSION="${REF}" ;;
          esac
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.dev
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          build-args: |
            LDFLAGS=-X 'main.version=${{ env.VERSION }}-${{ env.SHORT_SHA }}'
          tags: |
            ghcr.io/${{ github.repository }}:dev
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}-dev

  docker-alpine:
    name: Build and push alpine image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DAGU_GITHUB_TOKEN }}

      - name: Resolve version
        id: get_version
        shell: bash
        run: |
          REF="${{ inputs.ref }}"
          case "$REF" in
            refs/tags/v*) VERSION="${REF#refs/tags/v}" ;;
            v*)           VERSION="${REF#v}" ;;
            refs/tags/*)  VERSION="${REF#refs/tags/}" ;;
            *)            VERSION="${REF}" ;;
          esac
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.alpine
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          build-args: |
            LDFLAGS=-X 'main.version=${{ env.VERSION }}-${{ env.SHORT_SHA }}'
          tags: |
            ghcr.io/${{ github.repository }}:alpine
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}-alpine
