name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  # Build release binaries
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod

      - name: Set up NodeJS
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22

      - name: Set up pnpm
        run: npm install --global pnpm

      - name: pnpm install
        run: pnpm install
        working-directory: ui

      - name: Build web UI
        run: pnpm build
        working-directory: ui

      - name: Copy web assets
        run: cp ui/dist/* ./internal/service/frontend/assets/

      - name: Clean UI dependencies
        run: rm -rf ui/node_modules

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{secrets.DAGU_GITHUB_TOKEN}}
