/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Overview',
      items: [
        'intro',
        'getting-started',
        'command-usage',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Admin Settings',
      items: [
        'admin/environ',
        'admin/web-config',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Web Interface',
      items: [
        'web/dags',
        'web/detail',
        'web/history',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'YAML Format Reference',
      items: [
        'yaml/minimal',
        'yaml/with-environ',
        'yaml/with-params',
        'yaml/with-commands',
        'yaml/with-commands',
        'yaml/with-conditional',
        'yaml/with-handlers',
        'yaml/with-repeat',
        'yaml/all-fields',
        'yaml/global',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'See Also',
      items: [
        'see-also/faq',
        'see-also/architecture',
      ],
      collapsed: false,
    },
  ]
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
